// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.app.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.okta.app.outputs.GetSignOnPolicyRuleConditionsDeviceAssurance;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetSignOnPolicyRuleConditionsDevice {
    /**
     * @return Specifies device assurance policies in the policy rule.
     * 
     */
    private @Nullable GetSignOnPolicyRuleConditionsDeviceAssurance assurance;
    /**
     * @return Indicates if the device is managed.
     * 
     */
    private Boolean managed;
    /**
     * @return Indicates if the device is registered.
     * 
     */
    private Boolean registered;

    private GetSignOnPolicyRuleConditionsDevice() {}
    /**
     * @return Specifies device assurance policies in the policy rule.
     * 
     */
    public Optional<GetSignOnPolicyRuleConditionsDeviceAssurance> assurance() {
        return Optional.ofNullable(this.assurance);
    }
    /**
     * @return Indicates if the device is managed.
     * 
     */
    public Boolean managed() {
        return this.managed;
    }
    /**
     * @return Indicates if the device is registered.
     * 
     */
    public Boolean registered() {
        return this.registered;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSignOnPolicyRuleConditionsDevice defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetSignOnPolicyRuleConditionsDeviceAssurance assurance;
        private Boolean managed;
        private Boolean registered;
        public Builder() {}
        public Builder(GetSignOnPolicyRuleConditionsDevice defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.assurance = defaults.assurance;
    	      this.managed = defaults.managed;
    	      this.registered = defaults.registered;
        }

        @CustomType.Setter
        public Builder assurance(@Nullable GetSignOnPolicyRuleConditionsDeviceAssurance assurance) {

            this.assurance = assurance;
            return this;
        }
        @CustomType.Setter
        public Builder managed(Boolean managed) {
            if (managed == null) {
              throw new MissingRequiredPropertyException("GetSignOnPolicyRuleConditionsDevice", "managed");
            }
            this.managed = managed;
            return this;
        }
        @CustomType.Setter
        public Builder registered(Boolean registered) {
            if (registered == null) {
              throw new MissingRequiredPropertyException("GetSignOnPolicyRuleConditionsDevice", "registered");
            }
            this.registered = registered;
            return this;
        }
        public GetSignOnPolicyRuleConditionsDevice build() {
            final var _resultValue = new GetSignOnPolicyRuleConditionsDevice();
            _resultValue.assurance = assurance;
            _resultValue.managed = managed;
            _resultValue.registered = registered;
            return _resultValue;
        }
    }
}
