// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.idp.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetSamlArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSamlArgs Empty = new GetSamlArgs();

    /**
     * Id of idp.
     * 
     */
    @Import(name="id")
    private @Nullable Output<String> id;

    /**
     * @return Id of idp.
     * 
     */
    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * Name of the idp.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the idp.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private GetSamlArgs() {}

    private GetSamlArgs(GetSamlArgs $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSamlArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSamlArgs $;

        public Builder() {
            $ = new GetSamlArgs();
        }

        public Builder(GetSamlArgs defaults) {
            $ = new GetSamlArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id Id of idp.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Id of idp.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param name Name of the idp.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the idp.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetSamlArgs build() {
            return $;
        }
    }

}
