provider: okta
major-version: 6
esc:
    enabled: true
env:
    OKTA_BASE_URL: ${{ secrets.OKTA_BASE_URL }}
    OKTA_ORG_NAME: ${{ secrets.OKTA_ORG_NAME }}
    OKTA_API_TOKEN: ${{ secrets.OKTA_API_TOKEN }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
