// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta
{
    public static class GetApiToken
    {
        /// <summary>
        /// Use this data source to retrieve information about an Okta API token.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Okta = Pulumi.Okta;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Okta.GetApiToken.Invoke(new()
        ///     {
        ///         Id = "00T1fxzubpq2epw11d38",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetApiTokenResult> InvokeAsync(GetApiTokenArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetApiTokenResult>("okta:index/getApiToken:getApiToken", args ?? new GetApiTokenArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about an Okta API token.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Okta = Pulumi.Okta;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Okta.GetApiToken.Invoke(new()
        ///     {
        ///         Id = "00T1fxzubpq2epw11d38",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetApiTokenResult> Invoke(GetApiTokenInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetApiTokenResult>("okta:index/getApiToken:getApiToken", args ?? new GetApiTokenInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about an Okta API token.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Okta = Pulumi.Okta;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Okta.GetApiToken.Invoke(new()
        ///     {
        ///         Id = "00T1fxzubpq2epw11d38",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetApiTokenResult> Invoke(GetApiTokenInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetApiTokenResult>("okta:index/getApiToken:getApiToken", args ?? new GetApiTokenInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetApiTokenArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the API token.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The network configuration of the API token.
        /// </summary>
        [Input("network")]
        public Inputs.GetApiTokenNetworkArgs? Network { get; set; }

        public GetApiTokenArgs()
        {
        }
        public static new GetApiTokenArgs Empty => new GetApiTokenArgs();
    }

    public sealed class GetApiTokenInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The unique identifier of the API token.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The network configuration of the API token.
        /// </summary>
        [Input("network")]
        public Input<Inputs.GetApiTokenNetworkInputArgs>? Network { get; set; }

        public GetApiTokenInvokeArgs()
        {
        }
        public static new GetApiTokenInvokeArgs Empty => new GetApiTokenInvokeArgs();
    }


    [OutputType]
    public sealed class GetApiTokenResult
    {
        /// <summary>
        /// The name of the API token client.
        /// </summary>
        public readonly string ClientName;
        /// <summary>
        /// The date and time the API token was created.
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// The unique identifier of the API token.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the API token.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The network configuration of the API token.
        /// </summary>
        public readonly Outputs.GetApiTokenNetworkResult? Network;
        /// <summary>
        /// The userId of the user who created the API Token.
        /// </summary>
        public readonly string UserId;

        [OutputConstructor]
        private GetApiTokenResult(
            string clientName,

            string created,

            string id,

            string name,

            Outputs.GetApiTokenNetworkResult? network,

            string userId)
        {
            ClientName = clientName;
            Created = created;
            Id = id;
            Name = name;
            Network = network;
            UserId = userId;
        }
    }
}
