// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta
{
    public static class GetIamResourceSet
    {
        /// <summary>
        /// Retrieves a resource set by `resourceSetIdOrLabel`.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Okta = Pulumi.Okta;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Okta.GetIamResourceSet.Invoke(new()
        ///     {
        ///         Id = "&lt;resource_set_id_or_label&gt;",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetIamResourceSetResult> InvokeAsync(GetIamResourceSetArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetIamResourceSetResult>("okta:index/getIamResourceSet:getIamResourceSet", args ?? new GetIamResourceSetArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a resource set by `resourceSetIdOrLabel`.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Okta = Pulumi.Okta;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Okta.GetIamResourceSet.Invoke(new()
        ///     {
        ///         Id = "&lt;resource_set_id_or_label&gt;",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetIamResourceSetResult> Invoke(GetIamResourceSetInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetIamResourceSetResult>("okta:index/getIamResourceSet:getIamResourceSet", args ?? new GetIamResourceSetInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieves a resource set by `resourceSetIdOrLabel`.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Okta = Pulumi.Okta;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Okta.GetIamResourceSet.Invoke(new()
        ///     {
        ///         Id = "&lt;resource_set_id_or_label&gt;",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetIamResourceSetResult> Invoke(GetIamResourceSetInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetIamResourceSetResult>("okta:index/getIamResourceSet:getIamResourceSet", args ?? new GetIamResourceSetInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetIamResourceSetArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Unique identifier of the resource set.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetIamResourceSetArgs()
        {
        }
        public static new GetIamResourceSetArgs Empty => new GetIamResourceSetArgs();
    }

    public sealed class GetIamResourceSetInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Unique identifier of the resource set.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetIamResourceSetInvokeArgs()
        {
        }
        public static new GetIamResourceSetInvokeArgs Empty => new GetIamResourceSetInvokeArgs();
    }


    [OutputType]
    public sealed class GetIamResourceSetResult
    {
        /// <summary>
        /// Timestamp when the resource set was created.
        /// </summary>
        public readonly string Created;
        /// <summary>
        /// Description of the resource set.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// Unique identifier of the resource set.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Unique label for the resource set.
        /// </summary>
        public readonly string Label;
        /// <summary>
        /// Timestamp when the resource set was last updated.
        /// </summary>
        public readonly string LastUpdated;

        [OutputConstructor]
        private GetIamResourceSetResult(
            string created,

            string description,

            string id,

            string label,

            string lastUpdated)
        {
            Created = created;
            Description = description;
            Id = id;
            Label = label;
            LastUpdated = lastUpdated;
        }
    }
}
