// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta
{
    public static class GetOrgCaptcha
    {
        public static Task<GetOrgCaptchaResult> InvokeAsync(GetOrgCaptchaArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetOrgCaptchaResult>("okta:index/getOrgCaptcha:getOrgCaptcha", args ?? new GetOrgCaptchaArgs(), options.WithDefaults());

        public static Output<GetOrgCaptchaResult> Invoke(GetOrgCaptchaInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetOrgCaptchaResult>("okta:index/getOrgCaptcha:getOrgCaptcha", args ?? new GetOrgCaptchaInvokeArgs(), options.WithDefaults());

        public static Output<GetOrgCaptchaResult> Invoke(GetOrgCaptchaInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetOrgCaptchaResult>("okta:index/getOrgCaptcha:getOrgCaptcha", args ?? new GetOrgCaptchaInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetOrgCaptchaArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public string? Id { get; set; }

        public GetOrgCaptchaArgs()
        {
        }
        public static new GetOrgCaptchaArgs Empty => new GetOrgCaptchaArgs();
    }

    public sealed class GetOrgCaptchaInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        public GetOrgCaptchaInvokeArgs()
        {
        }
        public static new GetOrgCaptchaInvokeArgs Empty => new GetOrgCaptchaInvokeArgs();
    }


    [OutputType]
    public sealed class GetOrgCaptchaResult
    {
        public readonly string CaptchaId;
        public readonly ImmutableArray<string> EnabledPages;
        public readonly string Id;

        [OutputConstructor]
        private GetOrgCaptchaResult(
            string captchaId,

            ImmutableArray<string> enabledPages,

            string id)
        {
            CaptchaId = captchaId;
            EnabledPages = enabledPages;
            Id = id;
        }
    }
}
