// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta
{
    /// <summary>
    /// This resource allows the creation and manipulation of Okta Resource Sets as custom collections of Okta resources. You can use
    /// Okta Resource Sets to assign Custom Roles to administrators who are scoped to the designated resources.
    /// The `resources` field supports the following:
    ///  - Apps
    ///  - Groups
    ///  - All Users within a Group
    ///  - All Users within the org
    ///  - All Groups within the org
    ///  - All Apps within the org
    ///  - All Apps of the same type
    /// 
    /// &gt; **NOTE:** This an `Early Access` feature.
    /// 
    /// ## Import
    /// 
    /// Okta Resource Set can be imported via the Okta ID.
    /// 
    /// ```sh
    ///  $ pulumi import okta:index/resourceSet:ResourceSet example &lt;resource_set_id&gt;
    /// ```
    /// </summary>
    [OktaResourceType("okta:index/resourceSet:ResourceSet")]
    public partial class ResourceSet : Pulumi.CustomResource
    {
        /// <summary>
        /// A description of the Resource Set.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Unique name given to the Resource Set.
        /// </summary>
        [Output("label")]
        public Output<string> Label { get; private set; } = null!;

        /// <summary>
        /// The endpoints that reference the resources to be included in the new Resource Set. At least one
        /// endpoint must be specified when creating resource set.
        /// </summary>
        [Output("resources")]
        public Output<ImmutableArray<string>> Resources { get; private set; } = null!;


        /// <summary>
        /// Create a ResourceSet resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ResourceSet(string name, ResourceSetArgs args, CustomResourceOptions? options = null)
            : base("okta:index/resourceSet:ResourceSet", name, args ?? new ResourceSetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ResourceSet(string name, Input<string> id, ResourceSetState? state = null, CustomResourceOptions? options = null)
            : base("okta:index/resourceSet:ResourceSet", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ResourceSet resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ResourceSet Get(string name, Input<string> id, ResourceSetState? state = null, CustomResourceOptions? options = null)
        {
            return new ResourceSet(name, id, state, options);
        }
    }

    public sealed class ResourceSetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the Resource Set.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Unique name given to the Resource Set.
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        [Input("resources")]
        private InputList<string>? _resources;

        /// <summary>
        /// The endpoints that reference the resources to be included in the new Resource Set. At least one
        /// endpoint must be specified when creating resource set.
        /// </summary>
        public InputList<string> Resources
        {
            get => _resources ?? (_resources = new InputList<string>());
            set => _resources = value;
        }

        public ResourceSetArgs()
        {
        }
    }

    public sealed class ResourceSetState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the Resource Set.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Unique name given to the Resource Set.
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        [Input("resources")]
        private InputList<string>? _resources;

        /// <summary>
        /// The endpoints that reference the resources to be included in the new Resource Set. At least one
        /// endpoint must be specified when creating resource set.
        /// </summary>
        public InputList<string> Resources
        {
            get => _resources ?? (_resources = new InputList<string>());
            set => _resources = value;
        }

        public ResourceSetState()
        {
        }
    }
}
