// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package policy

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func LookupDefaultPolicy(ctx *pulumi.Context, args *GetDefaultPolicyArgs) (*GetDefaultPolicyResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["type"] = args.Type
	}
	outputs, err := ctx.Invoke("okta:policy/getDefaultPolicy:getDefaultPolicy", inputs)
	if err != nil {
		return nil, err
	}
	return &GetDefaultPolicyResult{
		Type: outputs["type"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getDefaultPolicy.
type GetDefaultPolicyArgs struct {
	Type interface{}
}

// A collection of values returned by getDefaultPolicy.
type GetDefaultPolicyResult struct {
	Type interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
