// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package idp

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Creates an Social Identity Provider.
// 
// This resource allows you to create and configure an Social Identity Provider.
//
// > This content is derived from https://github.com/articulate/terraform-provider-okta/blob/master/website/docs/r/idp_social.html.markdown.
type Social struct {
	s *pulumi.ResourceState
}

// NewSocial registers a new resource with the given unique name, arguments, and options.
func NewSocial(ctx *pulumi.Context,
	name string, args *SocialArgs, opts ...pulumi.ResourceOpt) (*Social, error) {
	if args == nil || args.Scopes == nil {
		return nil, errors.New("missing required argument 'Scopes'")
	}
	if args == nil || args.Type == nil {
		return nil, errors.New("missing required argument 'Type'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["accountLinkAction"] = nil
		inputs["accountLinkGroupIncludes"] = nil
		inputs["clientId"] = nil
		inputs["clientSecret"] = nil
		inputs["deprovisionedAction"] = nil
		inputs["groupsAction"] = nil
		inputs["groupsAssignments"] = nil
		inputs["groupsAttribute"] = nil
		inputs["groupsFilters"] = nil
		inputs["issuerMode"] = nil
		inputs["matchAttribute"] = nil
		inputs["matchType"] = nil
		inputs["maxClockSkew"] = nil
		inputs["name"] = nil
		inputs["profileMaster"] = nil
		inputs["protocolType"] = nil
		inputs["provisioningAction"] = nil
		inputs["requestSignatureAlgorithm"] = nil
		inputs["requestSignatureScope"] = nil
		inputs["responseSignatureAlgorithm"] = nil
		inputs["responseSignatureScope"] = nil
		inputs["scopes"] = nil
		inputs["status"] = nil
		inputs["subjectMatchAttribute"] = nil
		inputs["subjectMatchType"] = nil
		inputs["suspendedAction"] = nil
		inputs["type"] = nil
		inputs["usernameTemplate"] = nil
	} else {
		inputs["accountLinkAction"] = args.AccountLinkAction
		inputs["accountLinkGroupIncludes"] = args.AccountLinkGroupIncludes
		inputs["clientId"] = args.ClientId
		inputs["clientSecret"] = args.ClientSecret
		inputs["deprovisionedAction"] = args.DeprovisionedAction
		inputs["groupsAction"] = args.GroupsAction
		inputs["groupsAssignments"] = args.GroupsAssignments
		inputs["groupsAttribute"] = args.GroupsAttribute
		inputs["groupsFilters"] = args.GroupsFilters
		inputs["issuerMode"] = args.IssuerMode
		inputs["matchAttribute"] = args.MatchAttribute
		inputs["matchType"] = args.MatchType
		inputs["maxClockSkew"] = args.MaxClockSkew
		inputs["name"] = args.Name
		inputs["profileMaster"] = args.ProfileMaster
		inputs["protocolType"] = args.ProtocolType
		inputs["provisioningAction"] = args.ProvisioningAction
		inputs["requestSignatureAlgorithm"] = args.RequestSignatureAlgorithm
		inputs["requestSignatureScope"] = args.RequestSignatureScope
		inputs["responseSignatureAlgorithm"] = args.ResponseSignatureAlgorithm
		inputs["responseSignatureScope"] = args.ResponseSignatureScope
		inputs["scopes"] = args.Scopes
		inputs["status"] = args.Status
		inputs["subjectMatchAttribute"] = args.SubjectMatchAttribute
		inputs["subjectMatchType"] = args.SubjectMatchType
		inputs["suspendedAction"] = args.SuspendedAction
		inputs["type"] = args.Type
		inputs["usernameTemplate"] = args.UsernameTemplate
	}
	inputs["authorizationBinding"] = nil
	inputs["authorizationUrl"] = nil
	inputs["tokenBinding"] = nil
	inputs["tokenUrl"] = nil
	s, err := ctx.RegisterResource("okta:idp/social:Social", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Social{s: s}, nil
}

// GetSocial gets an existing Social resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSocial(ctx *pulumi.Context,
	name string, id pulumi.ID, state *SocialState, opts ...pulumi.ResourceOpt) (*Social, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["accountLinkAction"] = state.AccountLinkAction
		inputs["accountLinkGroupIncludes"] = state.AccountLinkGroupIncludes
		inputs["authorizationBinding"] = state.AuthorizationBinding
		inputs["authorizationUrl"] = state.AuthorizationUrl
		inputs["clientId"] = state.ClientId
		inputs["clientSecret"] = state.ClientSecret
		inputs["deprovisionedAction"] = state.DeprovisionedAction
		inputs["groupsAction"] = state.GroupsAction
		inputs["groupsAssignments"] = state.GroupsAssignments
		inputs["groupsAttribute"] = state.GroupsAttribute
		inputs["groupsFilters"] = state.GroupsFilters
		inputs["issuerMode"] = state.IssuerMode
		inputs["matchAttribute"] = state.MatchAttribute
		inputs["matchType"] = state.MatchType
		inputs["maxClockSkew"] = state.MaxClockSkew
		inputs["name"] = state.Name
		inputs["profileMaster"] = state.ProfileMaster
		inputs["protocolType"] = state.ProtocolType
		inputs["provisioningAction"] = state.ProvisioningAction
		inputs["requestSignatureAlgorithm"] = state.RequestSignatureAlgorithm
		inputs["requestSignatureScope"] = state.RequestSignatureScope
		inputs["responseSignatureAlgorithm"] = state.ResponseSignatureAlgorithm
		inputs["responseSignatureScope"] = state.ResponseSignatureScope
		inputs["scopes"] = state.Scopes
		inputs["status"] = state.Status
		inputs["subjectMatchAttribute"] = state.SubjectMatchAttribute
		inputs["subjectMatchType"] = state.SubjectMatchType
		inputs["suspendedAction"] = state.SuspendedAction
		inputs["tokenBinding"] = state.TokenBinding
		inputs["tokenUrl"] = state.TokenUrl
		inputs["type"] = state.Type
		inputs["usernameTemplate"] = state.UsernameTemplate
	}
	s, err := ctx.ReadResource("okta:idp/social:Social", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &Social{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *Social) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *Social) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// Specifies the account linking action for an IdP user.
func (r *Social) AccountLinkAction() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["accountLinkAction"])
}

// Group memberships to determine link candidates.
func (r *Social) AccountLinkGroupIncludes() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["accountLinkGroupIncludes"])
}

// The method of making an authorization request. It can be set to `"HTTP-POST"` or `"HTTP-REDIRECT"`.
func (r *Social) AuthorizationBinding() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["authorizationBinding"])
}

// IdP Authorization Server (AS) endpoint to request consent from the user and obtain an authorization code grant.
func (r *Social) AuthorizationUrl() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["authorizationUrl"])
}

// Unique identifier issued by AS for the Okta IdP instance.
func (r *Social) ClientId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["clientId"])
}

// Client secret issued by AS for the Okta IdP instance.
func (r *Social) ClientSecret() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["clientSecret"])
}

// Action for a previously deprovisioned IdP user during authentication. Can be `"NONE"` or `"REACTIVATE"`.
func (r *Social) DeprovisionedAction() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["deprovisionedAction"])
}

// Provisioning action for IdP user's group memberships. It can be `"NONE"`, `"SYNC"`, `"APPEND"`, or `"ASSIGN"`.
func (r *Social) GroupsAction() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["groupsAction"])
}

// List of Okta Group IDs to add an IdP user as a member with the `"ASSIGN"` `groupsAction`.
func (r *Social) GroupsAssignments() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["groupsAssignments"])
}

// IdP user profile attribute name (case-insensitive) for an array value that contains group memberships.
func (r *Social) GroupsAttribute() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["groupsAttribute"])
}

// Whitelist of Okta Group identifiers that are allowed for the `"APPEND"` or `"SYNC"` `groupsAction`.
func (r *Social) GroupsFilters() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["groupsFilters"])
}

// Indicates whether Okta uses the original Okta org domain URL, or a custom domain URL. It can be `"ORG_URL"` or `"CUSTOM_URL"`.
func (r *Social) IssuerMode() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["issuerMode"])
}

func (r *Social) MatchAttribute() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["matchAttribute"])
}

func (r *Social) MatchType() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["matchType"])
}

// Maximum allowable clock-skew when processing messages from the IdP.
func (r *Social) MaxClockSkew() *pulumi.IntOutput {
	return (*pulumi.IntOutput)(r.s.State["maxClockSkew"])
}

// The Application's display name.
func (r *Social) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Determines if the IdP should act as a source of truth for user profile attributes.
func (r *Social) ProfileMaster() *pulumi.BoolOutput {
	return (*pulumi.BoolOutput)(r.s.State["profileMaster"])
}

// The type of protocol to use. It can be `"OIDC"` or `"OAUTH2"`.
func (r *Social) ProtocolType() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["protocolType"])
}

// Provisioning action for an IdP user during authentication.
func (r *Social) ProvisioningAction() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["provisioningAction"])
}

// The XML digital signature algorithm used when signing an AuthnRequest message.
func (r *Social) RequestSignatureAlgorithm() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["requestSignatureAlgorithm"])
}

// Specifies whether or not to digitally sign an AuthnRequest messages to the IdP. It can be `"REQUEST"` or `"NONE"`.
func (r *Social) RequestSignatureScope() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["requestSignatureScope"])
}

// The minimum XML digital signature algorithm allowed when verifying a SAMLResponse message or Assertion element.
func (r *Social) ResponseSignatureAlgorithm() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["responseSignatureAlgorithm"])
}

// Specifies whether to verify a SAMLResponse message or Assertion element XML digital signature. It can be `"RESPONSE"`, `"ASSERTION"`, or `"ANY"`.
func (r *Social) ResponseSignatureScope() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["responseSignatureScope"])
}

// The scopes of the IdP.
func (r *Social) Scopes() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["scopes"])
}

// Status of the IdP.
func (r *Social) Status() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["status"])
}

// Okta user profile attribute for matching transformed IdP username. Only for matchType `"CUSTOM_ATTRIBUTE"`.
func (r *Social) SubjectMatchAttribute() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["subjectMatchAttribute"])
}

// Determines the Okta user profile attribute match conditions for account linking and authentication of the transformed IdP username. By default it is set to `"USERNAME"`. It can be set to `"USERNAME"`, `"EMAIL"`, `"USERNAME_OR_EMAIL"` or `"CUSTOM_ATTRIBUTE"`.
func (r *Social) SubjectMatchType() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["subjectMatchType"])
}

// Action for a previously suspended IdP user during authentication. Can be set to `"NONE"` or `"UNSUSPEND"`
func (r *Social) SuspendedAction() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["suspendedAction"])
}

// The method of making a token request. It can be set to `"HTTP-POST"` or `"HTTP-REDIRECT"`.
func (r *Social) TokenBinding() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["tokenBinding"])
}

// IdP Authorization Server (AS) endpoint to exchange the authorization code grant for an access token.
func (r *Social) TokenUrl() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["tokenUrl"])
}

// The type of Social IdP. It can be `"FACEBOOK"`, `"LINKEDIN"`, `"MICROSOFT"`, or `"GOOGLE"`.
func (r *Social) Type() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["type"])
}

// Okta EL Expression to generate or transform a unique username for the IdP user.
func (r *Social) UsernameTemplate() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["usernameTemplate"])
}

// Input properties used for looking up and filtering Social resources.
type SocialState struct {
	// Specifies the account linking action for an IdP user.
	AccountLinkAction interface{}
	// Group memberships to determine link candidates.
	AccountLinkGroupIncludes interface{}
	// The method of making an authorization request. It can be set to `"HTTP-POST"` or `"HTTP-REDIRECT"`.
	AuthorizationBinding interface{}
	// IdP Authorization Server (AS) endpoint to request consent from the user and obtain an authorization code grant.
	AuthorizationUrl interface{}
	// Unique identifier issued by AS for the Okta IdP instance.
	ClientId interface{}
	// Client secret issued by AS for the Okta IdP instance.
	ClientSecret interface{}
	// Action for a previously deprovisioned IdP user during authentication. Can be `"NONE"` or `"REACTIVATE"`.
	DeprovisionedAction interface{}
	// Provisioning action for IdP user's group memberships. It can be `"NONE"`, `"SYNC"`, `"APPEND"`, or `"ASSIGN"`.
	GroupsAction interface{}
	// List of Okta Group IDs to add an IdP user as a member with the `"ASSIGN"` `groupsAction`.
	GroupsAssignments interface{}
	// IdP user profile attribute name (case-insensitive) for an array value that contains group memberships.
	GroupsAttribute interface{}
	// Whitelist of Okta Group identifiers that are allowed for the `"APPEND"` or `"SYNC"` `groupsAction`.
	GroupsFilters interface{}
	// Indicates whether Okta uses the original Okta org domain URL, or a custom domain URL. It can be `"ORG_URL"` or `"CUSTOM_URL"`.
	IssuerMode interface{}
	MatchAttribute interface{}
	MatchType interface{}
	// Maximum allowable clock-skew when processing messages from the IdP.
	MaxClockSkew interface{}
	// The Application's display name.
	Name interface{}
	// Determines if the IdP should act as a source of truth for user profile attributes.
	ProfileMaster interface{}
	// The type of protocol to use. It can be `"OIDC"` or `"OAUTH2"`.
	ProtocolType interface{}
	// Provisioning action for an IdP user during authentication.
	ProvisioningAction interface{}
	// The XML digital signature algorithm used when signing an AuthnRequest message.
	RequestSignatureAlgorithm interface{}
	// Specifies whether or not to digitally sign an AuthnRequest messages to the IdP. It can be `"REQUEST"` or `"NONE"`.
	RequestSignatureScope interface{}
	// The minimum XML digital signature algorithm allowed when verifying a SAMLResponse message or Assertion element.
	ResponseSignatureAlgorithm interface{}
	// Specifies whether to verify a SAMLResponse message or Assertion element XML digital signature. It can be `"RESPONSE"`, `"ASSERTION"`, or `"ANY"`.
	ResponseSignatureScope interface{}
	// The scopes of the IdP.
	Scopes interface{}
	// Status of the IdP.
	Status interface{}
	// Okta user profile attribute for matching transformed IdP username. Only for matchType `"CUSTOM_ATTRIBUTE"`.
	SubjectMatchAttribute interface{}
	// Determines the Okta user profile attribute match conditions for account linking and authentication of the transformed IdP username. By default it is set to `"USERNAME"`. It can be set to `"USERNAME"`, `"EMAIL"`, `"USERNAME_OR_EMAIL"` or `"CUSTOM_ATTRIBUTE"`.
	SubjectMatchType interface{}
	// Action for a previously suspended IdP user during authentication. Can be set to `"NONE"` or `"UNSUSPEND"`
	SuspendedAction interface{}
	// The method of making a token request. It can be set to `"HTTP-POST"` or `"HTTP-REDIRECT"`.
	TokenBinding interface{}
	// IdP Authorization Server (AS) endpoint to exchange the authorization code grant for an access token.
	TokenUrl interface{}
	// The type of Social IdP. It can be `"FACEBOOK"`, `"LINKEDIN"`, `"MICROSOFT"`, or `"GOOGLE"`.
	Type interface{}
	// Okta EL Expression to generate or transform a unique username for the IdP user.
	UsernameTemplate interface{}
}

// The set of arguments for constructing a Social resource.
type SocialArgs struct {
	// Specifies the account linking action for an IdP user.
	AccountLinkAction interface{}
	// Group memberships to determine link candidates.
	AccountLinkGroupIncludes interface{}
	// Unique identifier issued by AS for the Okta IdP instance.
	ClientId interface{}
	// Client secret issued by AS for the Okta IdP instance.
	ClientSecret interface{}
	// Action for a previously deprovisioned IdP user during authentication. Can be `"NONE"` or `"REACTIVATE"`.
	DeprovisionedAction interface{}
	// Provisioning action for IdP user's group memberships. It can be `"NONE"`, `"SYNC"`, `"APPEND"`, or `"ASSIGN"`.
	GroupsAction interface{}
	// List of Okta Group IDs to add an IdP user as a member with the `"ASSIGN"` `groupsAction`.
	GroupsAssignments interface{}
	// IdP user profile attribute name (case-insensitive) for an array value that contains group memberships.
	GroupsAttribute interface{}
	// Whitelist of Okta Group identifiers that are allowed for the `"APPEND"` or `"SYNC"` `groupsAction`.
	GroupsFilters interface{}
	// Indicates whether Okta uses the original Okta org domain URL, or a custom domain URL. It can be `"ORG_URL"` or `"CUSTOM_URL"`.
	IssuerMode interface{}
	MatchAttribute interface{}
	MatchType interface{}
	// Maximum allowable clock-skew when processing messages from the IdP.
	MaxClockSkew interface{}
	// The Application's display name.
	Name interface{}
	// Determines if the IdP should act as a source of truth for user profile attributes.
	ProfileMaster interface{}
	// The type of protocol to use. It can be `"OIDC"` or `"OAUTH2"`.
	ProtocolType interface{}
	// Provisioning action for an IdP user during authentication.
	ProvisioningAction interface{}
	// The XML digital signature algorithm used when signing an AuthnRequest message.
	RequestSignatureAlgorithm interface{}
	// Specifies whether or not to digitally sign an AuthnRequest messages to the IdP. It can be `"REQUEST"` or `"NONE"`.
	RequestSignatureScope interface{}
	// The minimum XML digital signature algorithm allowed when verifying a SAMLResponse message or Assertion element.
	ResponseSignatureAlgorithm interface{}
	// Specifies whether to verify a SAMLResponse message or Assertion element XML digital signature. It can be `"RESPONSE"`, `"ASSERTION"`, or `"ANY"`.
	ResponseSignatureScope interface{}
	// The scopes of the IdP.
	Scopes interface{}
	// Status of the IdP.
	Status interface{}
	// Okta user profile attribute for matching transformed IdP username. Only for matchType `"CUSTOM_ATTRIBUTE"`.
	SubjectMatchAttribute interface{}
	// Determines the Okta user profile attribute match conditions for account linking and authentication of the transformed IdP username. By default it is set to `"USERNAME"`. It can be set to `"USERNAME"`, `"EMAIL"`, `"USERNAME_OR_EMAIL"` or `"CUSTOM_ATTRIBUTE"`.
	SubjectMatchType interface{}
	// Action for a previously suspended IdP user during authentication. Can be set to `"NONE"` or `"UNSUSPEND"`
	SuspendedAction interface{}
	// The type of Social IdP. It can be `"FACEBOOK"`, `"LINKEDIN"`, `"MICROSOFT"`, or `"GOOGLE"`.
	Type interface{}
	// Okta EL Expression to generate or transform a unique username for the IdP user.
	UsernameTemplate interface{}
}
