// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package app

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

// Creates an Auto Login Okta Application.
//
// This resource allows you to create and configure an Auto Login Okta Application.
type AutoLogin struct {
	pulumi.CustomResourceState

	// Custom error page URL
	AccessibilityErrorRedirectUrl pulumi.StringPtrOutput `pulumi:"accessibilityErrorRedirectUrl"`
	// Enable self service
	AccessibilitySelfService pulumi.BoolPtrOutput `pulumi:"accessibilitySelfService"`
	// Display auto submit toolbar
	AutoSubmitToolbar pulumi.BoolPtrOutput `pulumi:"autoSubmitToolbar"`
	// Application credentials scheme
	CredentialsScheme pulumi.StringPtrOutput `pulumi:"credentialsScheme"`
	// Groups associated with the application
	Groups pulumi.StringArrayOutput `pulumi:"groups"`
	// Do not display application icon on mobile app
	HideIos pulumi.BoolPtrOutput `pulumi:"hideIos"`
	// Do not display application icon to users
	HideWeb pulumi.BoolPtrOutput `pulumi:"hideWeb"`
	// The Application's display name.
	Label pulumi.StringOutput `pulumi:"label"`
	// Name assigned to the application by Okta.
	Name pulumi.StringOutput `pulumi:"name"`
	// Tells Okta to use an existing application in their application catalog, as opposed to a custom application.
	PreconfiguredApp pulumi.StringPtrOutput `pulumi:"preconfiguredApp"`
	// Allow user to reveal password
	RevealPassword pulumi.BoolPtrOutput `pulumi:"revealPassword"`
	// Shared password, required for certain schemes.
	SharedPassword pulumi.StringPtrOutput `pulumi:"sharedPassword"`
	// Shared username, required for certain schemes.
	SharedUsername pulumi.StringPtrOutput `pulumi:"sharedUsername"`
	// Sign on mode of application.
	SignOnMode pulumi.StringOutput `pulumi:"signOnMode"`
	// Post login redirect URL
	SignOnRedirectUrl pulumi.StringPtrOutput `pulumi:"signOnRedirectUrl"`
	// Login URL
	SignOnUrl pulumi.StringPtrOutput `pulumi:"signOnUrl"`
	// The status of the application, by default it is `"ACTIVE"`.
	Status pulumi.StringPtrOutput `pulumi:"status"`
	// Username template
	UserNameTemplate pulumi.StringOutput `pulumi:"userNameTemplate"`
	// Username template type
	UserNameTemplateType pulumi.StringOutput `pulumi:"userNameTemplateType"`
	// Users associated with the application
	Users AutoLoginUserArrayOutput `pulumi:"users"`
}

// NewAutoLogin registers a new resource with the given unique name, arguments, and options.
func NewAutoLogin(ctx *pulumi.Context,
	name string, args *AutoLoginArgs, opts ...pulumi.ResourceOption) (*AutoLogin, error) {
	if args == nil || args.Label == nil {
		return nil, errors.New("missing required argument 'Label'")
	}
	if args == nil {
		args = &AutoLoginArgs{}
	}
	var resource AutoLogin
	err := ctx.RegisterResource("okta:app/autoLogin:AutoLogin", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAutoLogin gets an existing AutoLogin resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAutoLogin(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AutoLoginState, opts ...pulumi.ResourceOption) (*AutoLogin, error) {
	var resource AutoLogin
	err := ctx.ReadResource("okta:app/autoLogin:AutoLogin", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AutoLogin resources.
type autoLoginState struct {
	// Custom error page URL
	AccessibilityErrorRedirectUrl *string `pulumi:"accessibilityErrorRedirectUrl"`
	// Enable self service
	AccessibilitySelfService *bool `pulumi:"accessibilitySelfService"`
	// Display auto submit toolbar
	AutoSubmitToolbar *bool `pulumi:"autoSubmitToolbar"`
	// Application credentials scheme
	CredentialsScheme *string `pulumi:"credentialsScheme"`
	// Groups associated with the application
	Groups []string `pulumi:"groups"`
	// Do not display application icon on mobile app
	HideIos *bool `pulumi:"hideIos"`
	// Do not display application icon to users
	HideWeb *bool `pulumi:"hideWeb"`
	// The Application's display name.
	Label *string `pulumi:"label"`
	// Name assigned to the application by Okta.
	Name *string `pulumi:"name"`
	// Tells Okta to use an existing application in their application catalog, as opposed to a custom application.
	PreconfiguredApp *string `pulumi:"preconfiguredApp"`
	// Allow user to reveal password
	RevealPassword *bool `pulumi:"revealPassword"`
	// Shared password, required for certain schemes.
	SharedPassword *string `pulumi:"sharedPassword"`
	// Shared username, required for certain schemes.
	SharedUsername *string `pulumi:"sharedUsername"`
	// Sign on mode of application.
	SignOnMode *string `pulumi:"signOnMode"`
	// Post login redirect URL
	SignOnRedirectUrl *string `pulumi:"signOnRedirectUrl"`
	// Login URL
	SignOnUrl *string `pulumi:"signOnUrl"`
	// The status of the application, by default it is `"ACTIVE"`.
	Status *string `pulumi:"status"`
	// Username template
	UserNameTemplate *string `pulumi:"userNameTemplate"`
	// Username template type
	UserNameTemplateType *string `pulumi:"userNameTemplateType"`
	// Users associated with the application
	Users []AutoLoginUser `pulumi:"users"`
}

type AutoLoginState struct {
	// Custom error page URL
	AccessibilityErrorRedirectUrl pulumi.StringPtrInput
	// Enable self service
	AccessibilitySelfService pulumi.BoolPtrInput
	// Display auto submit toolbar
	AutoSubmitToolbar pulumi.BoolPtrInput
	// Application credentials scheme
	CredentialsScheme pulumi.StringPtrInput
	// Groups associated with the application
	Groups pulumi.StringArrayInput
	// Do not display application icon on mobile app
	HideIos pulumi.BoolPtrInput
	// Do not display application icon to users
	HideWeb pulumi.BoolPtrInput
	// The Application's display name.
	Label pulumi.StringPtrInput
	// Name assigned to the application by Okta.
	Name pulumi.StringPtrInput
	// Tells Okta to use an existing application in their application catalog, as opposed to a custom application.
	PreconfiguredApp pulumi.StringPtrInput
	// Allow user to reveal password
	RevealPassword pulumi.BoolPtrInput
	// Shared password, required for certain schemes.
	SharedPassword pulumi.StringPtrInput
	// Shared username, required for certain schemes.
	SharedUsername pulumi.StringPtrInput
	// Sign on mode of application.
	SignOnMode pulumi.StringPtrInput
	// Post login redirect URL
	SignOnRedirectUrl pulumi.StringPtrInput
	// Login URL
	SignOnUrl pulumi.StringPtrInput
	// The status of the application, by default it is `"ACTIVE"`.
	Status pulumi.StringPtrInput
	// Username template
	UserNameTemplate pulumi.StringPtrInput
	// Username template type
	UserNameTemplateType pulumi.StringPtrInput
	// Users associated with the application
	Users AutoLoginUserArrayInput
}

func (AutoLoginState) ElementType() reflect.Type {
	return reflect.TypeOf((*autoLoginState)(nil)).Elem()
}

type autoLoginArgs struct {
	// Custom error page URL
	AccessibilityErrorRedirectUrl *string `pulumi:"accessibilityErrorRedirectUrl"`
	// Enable self service
	AccessibilitySelfService *bool `pulumi:"accessibilitySelfService"`
	// Display auto submit toolbar
	AutoSubmitToolbar *bool `pulumi:"autoSubmitToolbar"`
	// Application credentials scheme
	CredentialsScheme *string `pulumi:"credentialsScheme"`
	// Groups associated with the application
	Groups []string `pulumi:"groups"`
	// Do not display application icon on mobile app
	HideIos *bool `pulumi:"hideIos"`
	// Do not display application icon to users
	HideWeb *bool `pulumi:"hideWeb"`
	// The Application's display name.
	Label string `pulumi:"label"`
	// Tells Okta to use an existing application in their application catalog, as opposed to a custom application.
	PreconfiguredApp *string `pulumi:"preconfiguredApp"`
	// Allow user to reveal password
	RevealPassword *bool `pulumi:"revealPassword"`
	// Shared password, required for certain schemes.
	SharedPassword *string `pulumi:"sharedPassword"`
	// Shared username, required for certain schemes.
	SharedUsername *string `pulumi:"sharedUsername"`
	// Post login redirect URL
	SignOnRedirectUrl *string `pulumi:"signOnRedirectUrl"`
	// Login URL
	SignOnUrl *string `pulumi:"signOnUrl"`
	// The status of the application, by default it is `"ACTIVE"`.
	Status *string `pulumi:"status"`
	// Users associated with the application
	Users []AutoLoginUser `pulumi:"users"`
}

// The set of arguments for constructing a AutoLogin resource.
type AutoLoginArgs struct {
	// Custom error page URL
	AccessibilityErrorRedirectUrl pulumi.StringPtrInput
	// Enable self service
	AccessibilitySelfService pulumi.BoolPtrInput
	// Display auto submit toolbar
	AutoSubmitToolbar pulumi.BoolPtrInput
	// Application credentials scheme
	CredentialsScheme pulumi.StringPtrInput
	// Groups associated with the application
	Groups pulumi.StringArrayInput
	// Do not display application icon on mobile app
	HideIos pulumi.BoolPtrInput
	// Do not display application icon to users
	HideWeb pulumi.BoolPtrInput
	// The Application's display name.
	Label pulumi.StringInput
	// Tells Okta to use an existing application in their application catalog, as opposed to a custom application.
	PreconfiguredApp pulumi.StringPtrInput
	// Allow user to reveal password
	RevealPassword pulumi.BoolPtrInput
	// Shared password, required for certain schemes.
	SharedPassword pulumi.StringPtrInput
	// Shared username, required for certain schemes.
	SharedUsername pulumi.StringPtrInput
	// Post login redirect URL
	SignOnRedirectUrl pulumi.StringPtrInput
	// Login URL
	SignOnUrl pulumi.StringPtrInput
	// The status of the application, by default it is `"ACTIVE"`.
	Status pulumi.StringPtrInput
	// Users associated with the application
	Users AutoLoginUserArrayInput
}

func (AutoLoginArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*autoLoginArgs)(nil)).Elem()
}
