// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.group.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GroupState extends com.pulumi.resources.ResourceArgs {

    public static final GroupState Empty = new GroupState();

    /**
     * raw JSON containing all custom profile attributes.
     * 
     */
    @Import(name="customProfileAttributes")
    private @Nullable Output<String> customProfileAttributes;

    /**
     * @return raw JSON containing all custom profile attributes.
     * 
     */
    public Optional<Output<String>> customProfileAttributes() {
        return Optional.ofNullable(this.customProfileAttributes);
    }

    /**
     * The description of the Okta Group.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the Okta Group.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The name of the Okta Group.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the Okta Group.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Indicator that allows a group to skip `users` sync (it&#39;s also can be provided during import). Default is `false`.
     * 
     */
    @Import(name="skipUsers")
    private @Nullable Output<Boolean> skipUsers;

    /**
     * @return Indicator that allows a group to skip `users` sync (it&#39;s also can be provided during import). Default is `false`.
     * 
     */
    public Optional<Output<Boolean>> skipUsers() {
        return Optional.ofNullable(this.skipUsers);
    }

    /**
     * The users associated with the group. This can also be done per user.
     * `DEPRECATED`: Please replace usage with the `okta.GroupMemberships` resource.
     * 
     * @deprecated
     * The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships`
     * 
     */
    @Deprecated /* The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships` */
    @Import(name="users")
    private @Nullable Output<List<String>> users;

    /**
     * @return The users associated with the group. This can also be done per user.
     * `DEPRECATED`: Please replace usage with the `okta.GroupMemberships` resource.
     * 
     * @deprecated
     * The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships`
     * 
     */
    @Deprecated /* The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships` */
    public Optional<Output<List<String>>> users() {
        return Optional.ofNullable(this.users);
    }

    private GroupState() {}

    private GroupState(GroupState $) {
        this.customProfileAttributes = $.customProfileAttributes;
        this.description = $.description;
        this.name = $.name;
        this.skipUsers = $.skipUsers;
        this.users = $.users;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GroupState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GroupState $;

        public Builder() {
            $ = new GroupState();
        }

        public Builder(GroupState defaults) {
            $ = new GroupState(Objects.requireNonNull(defaults));
        }

        /**
         * @param customProfileAttributes raw JSON containing all custom profile attributes.
         * 
         * @return builder
         * 
         */
        public Builder customProfileAttributes(@Nullable Output<String> customProfileAttributes) {
            $.customProfileAttributes = customProfileAttributes;
            return this;
        }

        /**
         * @param customProfileAttributes raw JSON containing all custom profile attributes.
         * 
         * @return builder
         * 
         */
        public Builder customProfileAttributes(String customProfileAttributes) {
            return customProfileAttributes(Output.of(customProfileAttributes));
        }

        /**
         * @param description The description of the Okta Group.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the Okta Group.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name The name of the Okta Group.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the Okta Group.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param skipUsers Indicator that allows a group to skip `users` sync (it&#39;s also can be provided during import). Default is `false`.
         * 
         * @return builder
         * 
         */
        public Builder skipUsers(@Nullable Output<Boolean> skipUsers) {
            $.skipUsers = skipUsers;
            return this;
        }

        /**
         * @param skipUsers Indicator that allows a group to skip `users` sync (it&#39;s also can be provided during import). Default is `false`.
         * 
         * @return builder
         * 
         */
        public Builder skipUsers(Boolean skipUsers) {
            return skipUsers(Output.of(skipUsers));
        }

        /**
         * @param users The users associated with the group. This can also be done per user.
         * `DEPRECATED`: Please replace usage with the `okta.GroupMemberships` resource.
         * 
         * @return builder
         * 
         * @deprecated
         * The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships`
         * 
         */
        @Deprecated /* The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships` */
        public Builder users(@Nullable Output<List<String>> users) {
            $.users = users;
            return this;
        }

        /**
         * @param users The users associated with the group. This can also be done per user.
         * `DEPRECATED`: Please replace usage with the `okta.GroupMemberships` resource.
         * 
         * @return builder
         * 
         * @deprecated
         * The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships`
         * 
         */
        @Deprecated /* The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships` */
        public Builder users(List<String> users) {
            return users(Output.of(users));
        }

        /**
         * @param users The users associated with the group. This can also be done per user.
         * `DEPRECATED`: Please replace usage with the `okta.GroupMemberships` resource.
         * 
         * @return builder
         * 
         * @deprecated
         * The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships`
         * 
         */
        @Deprecated /* The `users` field is now deprecated for the resource `okta_group`, please replace all uses of this with: `okta_group_memberships` */
        public Builder users(String... users) {
            return users(List.of(users));
        }

        public GroupState build() {
            return $;
        }
    }

}
