// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.Index;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.okta.Index.EmailDomainArgs;
import com.pulumi.okta.Index.inputs.EmailDomainState;
import com.pulumi.okta.Index.outputs.EmailDomainDnsValidationRecord;
import com.pulumi.okta.Utilities;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * This resource allows you to create and configure an email domain.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.okta.Index.EmailDomain;
 * import com.pulumi.okta.Index.EmailDomainArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new EmailDomain("example", EmailDomainArgs.builder()        
 *             .brandId("abc123")
 *             .domain("example.com")
 *             .displayName("test")
 *             .userName("paul_atreides")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * Custom email domain can be imported via the Okta ID.
 * 
 * ```sh
 * $ pulumi import okta:Index/emailDomain:EmailDomain example &amp;#60;domain id&amp;#62;
 * ```
 * 
 */
@ResourceType(type="okta:Index/emailDomain:EmailDomain")
public class EmailDomain extends com.pulumi.resources.CustomResource {
    /**
     * Brand id of the email domain.
     * 
     */
    @Export(name="brandId", refs={String.class}, tree="[0]")
    private Output<String> brandId;

    /**
     * @return Brand id of the email domain.
     * 
     */
    public Output<String> brandId() {
        return this.brandId;
    }
    /**
     * Display name of the email domain.
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return Display name of the email domain.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * TXT and CNAME records to be registered for the domain.
     * 
     */
    @Export(name="dnsValidationRecords", refs={List.class,EmailDomainDnsValidationRecord.class}, tree="[0,1]")
    private Output<List<EmailDomainDnsValidationRecord>> dnsValidationRecords;

    /**
     * @return TXT and CNAME records to be registered for the domain.
     * 
     */
    public Output<List<EmailDomainDnsValidationRecord>> dnsValidationRecords() {
        return this.dnsValidationRecords;
    }
    /**
     * Mail domain to send from.
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    /**
     * @return Mail domain to send from.
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }
    /**
     * User name of the email domain.
     * 
     */
    @Export(name="userName", refs={String.class}, tree="[0]")
    private Output<String> userName;

    /**
     * @return User name of the email domain.
     * 
     */
    public Output<String> userName() {
        return this.userName;
    }
    /**
     * Status of the email domain (shows whether the domain is verified).
     * 
     */
    @Export(name="validationStatus", refs={String.class}, tree="[0]")
    private Output<String> validationStatus;

    /**
     * @return Status of the email domain (shows whether the domain is verified).
     * 
     */
    public Output<String> validationStatus() {
        return this.validationStatus;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public EmailDomain(String name) {
        this(name, EmailDomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public EmailDomain(String name, EmailDomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public EmailDomain(String name, EmailDomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("okta:Index/emailDomain:EmailDomain", name, args == null ? EmailDomainArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private EmailDomain(String name, Output<String> id, @Nullable EmailDomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("okta:Index/emailDomain:EmailDomain", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static EmailDomain get(String name, Output<String> id, @Nullable EmailDomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new EmailDomain(name, id, state, options);
    }
}
