# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIdentitySourceUsersResult',
    'AwaitableGetIdentitySourceUsersResult',
    'get_identity_source_users',
    'get_identity_source_users_output',
]

@pulumi.output_type
class GetIdentitySourceUsersResult:
    """
    A collection of values returned by getIdentitySourceUsers.
    """
    def __init__(__self__, created=None, external_id=None, id=None, identity_source_id=None, last_updated=None, profile=None):
        if created and not isinstance(created, str):
            raise TypeError("Expected argument 'created' to be a str")
        pulumi.set(__self__, "created", created)
        if external_id and not isinstance(external_id, str):
            raise TypeError("Expected argument 'external_id' to be a str")
        pulumi.set(__self__, "external_id", external_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if identity_source_id and not isinstance(identity_source_id, str):
            raise TypeError("Expected argument 'identity_source_id' to be a str")
        pulumi.set(__self__, "identity_source_id", identity_source_id)
        if last_updated and not isinstance(last_updated, str):
            raise TypeError("Expected argument 'last_updated' to be a str")
        pulumi.set(__self__, "last_updated", last_updated)
        if profile and not isinstance(profile, dict):
            raise TypeError("Expected argument 'profile' to be a dict")
        pulumi.set(__self__, "profile", profile)

    @_builtins.property
    @pulumi.getter
    def created(self) -> _builtins.str:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="externalId")
    def external_id(self) -> _builtins.str:
        return pulumi.get(self, "external_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="identitySourceId")
    def identity_source_id(self) -> _builtins.str:
        return pulumi.get(self, "identity_source_id")

    @_builtins.property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> _builtins.str:
        return pulumi.get(self, "last_updated")

    @_builtins.property
    @pulumi.getter
    def profile(self) -> 'outputs.GetIdentitySourceUsersProfileResult':
        return pulumi.get(self, "profile")


class AwaitableGetIdentitySourceUsersResult(GetIdentitySourceUsersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIdentitySourceUsersResult(
            created=self.created,
            external_id=self.external_id,
            id=self.id,
            identity_source_id=self.identity_source_id,
            last_updated=self.last_updated,
            profile=self.profile)


def get_identity_source_users(external_id: Optional[_builtins.str] = None,
                              id: Optional[_builtins.str] = None,
                              identity_source_id: Optional[_builtins.str] = None,
                              opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIdentitySourceUsersResult:
    """
    Retrieves a user record from an Okta Identity Source by external ID.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_okta as okta

    example = okta.get_identity_source_users(identity_source_id="<identity-source-id>",
        external_id="USEREXT123456EXAMPLE")
    pulumi.export("userEmail", example.profile.email)
    ```
    """
    __args__ = dict()
    __args__['externalId'] = external_id
    __args__['id'] = id
    __args__['identitySourceId'] = identity_source_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('okta:index/getIdentitySourceUsers:getIdentitySourceUsers', __args__, opts=opts, typ=GetIdentitySourceUsersResult).value

    return AwaitableGetIdentitySourceUsersResult(
        created=pulumi.get(__ret__, 'created'),
        external_id=pulumi.get(__ret__, 'external_id'),
        id=pulumi.get(__ret__, 'id'),
        identity_source_id=pulumi.get(__ret__, 'identity_source_id'),
        last_updated=pulumi.get(__ret__, 'last_updated'),
        profile=pulumi.get(__ret__, 'profile'))
def get_identity_source_users_output(external_id: pulumi.Input[Optional[_builtins.str]] = None,
                                     id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                     identity_source_id: pulumi.Input[Optional[_builtins.str]] = None,
                                     opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIdentitySourceUsersResult]:
    """
    Retrieves a user record from an Okta Identity Source by external ID.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_okta as okta

    example = okta.get_identity_source_users(identity_source_id="<identity-source-id>",
        external_id="USEREXT123456EXAMPLE")
    pulumi.export("userEmail", example.profile.email)
    ```
    """
    __args__ = dict()
    __args__['externalId'] = external_id
    __args__['id'] = id
    __args__['identitySourceId'] = identity_source_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('okta:index/getIdentitySourceUsers:getIdentitySourceUsers', __args__, opts=opts, typ=GetIdentitySourceUsersResult)
    return __ret__.apply(lambda __response__: GetIdentitySourceUsersResult(
        created=pulumi.get(__response__, 'created'),
        external_id=pulumi.get(__response__, 'external_id'),
        id=pulumi.get(__response__, 'id'),
        identity_source_id=pulumi.get(__response__, 'identity_source_id'),
        last_updated=pulumi.get(__response__, 'last_updated'),
        profile=pulumi.get(__response__, 'profile')))
