// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.deprecated.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SignonPolicyRuleFactorSequenceSecondaryCriteria {
    private String factorType;
    private String provider;

    private SignonPolicyRuleFactorSequenceSecondaryCriteria() {}
    public String factorType() {
        return this.factorType;
    }
    public String provider() {
        return this.provider;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SignonPolicyRuleFactorSequenceSecondaryCriteria defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String factorType;
        private String provider;
        public Builder() {}
        public Builder(SignonPolicyRuleFactorSequenceSecondaryCriteria defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.factorType = defaults.factorType;
    	      this.provider = defaults.provider;
        }

        @CustomType.Setter
        public Builder factorType(String factorType) {
            this.factorType = Objects.requireNonNull(factorType);
            return this;
        }
        @CustomType.Setter
        public Builder provider(String provider) {
            this.provider = Objects.requireNonNull(provider);
            return this;
        }
        public SignonPolicyRuleFactorSequenceSecondaryCriteria build() {
            final var o = new SignonPolicyRuleFactorSequenceSecondaryCriteria();
            o.factorType = factorType;
            o.provider = provider;
            return o;
        }
    }
}
