// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Outputs
{

    [OutputType]
    public sealed class GetAuthServerClaimsClaimResult
    {
        public readonly bool AlwaysIncludeInToken;
        public readonly string ClaimType;
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<string> Scopes;
        public readonly string Status;
        public readonly string Value;
        public readonly string ValueType;

        [OutputConstructor]
        private GetAuthServerClaimsClaimResult(
            bool alwaysIncludeInToken,

            string claimType,

            string id,

            string name,

            ImmutableArray<string> scopes,

            string status,

            string value,

            string valueType)
        {
            AlwaysIncludeInToken = alwaysIncludeInToken;
            ClaimType = claimType;
            Id = id;
            Name = name;
            Scopes = scopes;
            Status = status;
            Value = value;
            ValueType = valueType;
        }
    }
}
