// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Outputs
{

    [OutputType]
    public sealed class GetPushProviderConfigurationFcmConfigurationServiceAccountJsonResult
    {
        /// <summary>
        /// File name for Admin Console display.
        /// </summary>
        public readonly string FileName;
        /// <summary>
        /// The project ID.
        /// </summary>
        public readonly string ProjectId;

        [OutputConstructor]
        private GetPushProviderConfigurationFcmConfigurationServiceAccountJsonResult(
            string fileName,

            string projectId)
        {
            FileName = fileName;
            ProjectId = projectId;
        }
    }
}
