// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Outputs
{

    [OutputType]
    public sealed class GetRequestSettingResourceValidAccessDurationSettingsResult
    {
        /// <summary>
        /// The maximum value allowed for a request condition or risk setting.
        /// </summary>
        public readonly double MaximumDays;
        /// <summary>
        /// The maximum value allowed for a request condition or risk setting.
        /// </summary>
        public readonly double MaximumHours;
        /// <summary>
        /// The maximum value allowed for a request condition or risk setting.
        /// </summary>
        public readonly double MaximumWeeks;
        /// <summary>
        /// Whether accessDurationSetting must be included in the request conditions or risk settings for the specified resource.
        /// </summary>
        public readonly bool Required;
        /// <summary>
        /// Access duration settings that are eligible to be added to a request condition or risk settings for the specified resource.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetRequestSettingResourceValidAccessDurationSettingsSupportedTypeResult> SupportedTypes;

        [OutputConstructor]
        private GetRequestSettingResourceValidAccessDurationSettingsResult(
            double maximumDays,

            double maximumHours,

            double maximumWeeks,

            bool required,

            ImmutableArray<Outputs.GetRequestSettingResourceValidAccessDurationSettingsSupportedTypeResult> supportedTypes)
        {
            MaximumDays = maximumDays;
            MaximumHours = maximumHours;
            MaximumWeeks = maximumWeeks;
            Required = required;
            SupportedTypes = supportedTypes;
        }
    }
}
