// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Outputs
{

    [OutputType]
    public sealed class GetTemplatesEmailTemplateResult
    {
        /// <summary>
        /// Link relations for this object - JSON HAL - Discoverable resources related to the email template
        /// </summary>
        public readonly string Links;
        /// <summary>
        /// The name of the email template
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private GetTemplatesEmailTemplateResult(
            string links,

            string name)
        {
            Links = links;
            Name = name;
        }
    }
}
