// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Outputs
{

    [OutputType]
    public sealed class RequestSettingResourceRiskSettings
    {
        /// <summary>
        /// Default risk settings that are valid for an access request when a risk has been detected for the resource and requesting user.
        /// </summary>
        public readonly Outputs.RequestSettingResourceRiskSettingsDefaultSetting? DefaultSetting;

        [OutputConstructor]
        private RequestSettingResourceRiskSettings(Outputs.RequestSettingResourceRiskSettingsDefaultSetting? defaultSetting)
        {
            DefaultSetting = defaultSetting;
        }
    }
}
