// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Outputs
{

    [OutputType]
    public sealed class SecurityEventsProviderSettings
    {
        /// <summary>
        /// Issuer URL. Maximum length: 700 characters. To be used along with `JwksUrl`.
        /// </summary>
        public readonly string? Issuer;
        /// <summary>
        /// The public URL where the JWKS public key is uploaded. Maximum length: 1000 characters. To be used along with `Issuer`.
        /// </summary>
        public readonly string? JwksUrl;
        /// <summary>
        /// The published well-known URL of the Security Events Provider (the SSF transmitter). Maximum length: 1000 characters.
        /// </summary>
        public readonly string? WellKnownUrl;

        [OutputConstructor]
        private SecurityEventsProviderSettings(
            string? issuer,

            string? jwksUrl,

            string? wellKnownUrl)
        {
            Issuer = issuer;
            JwksUrl = jwksUrl;
            WellKnownUrl = wellKnownUrl;
        }
    }
}
