// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package okta

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a SWA shared credentials app.
//
// This resource allows you to create and configure SWA shared credentials app.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-okta/sdk/v3/go/okta"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := okta.NewAppSharedCredentials(ctx, "example", &okta.AppSharedCredentialsArgs{
// 			AccessibilityErrorRedirectUrl: pulumi.String("https://example.com/redirect_url_1"),
// 			AccessibilityLoginRedirectUrl: pulumi.String("https://example.com/redirect_url_2"),
// 			AccessibilitySelfService:      pulumi.Bool(true),
// 			AutoSubmitToolbar:             pulumi.Bool(true),
// 			ButtonField:                   pulumi.String("btn-login"),
// 			Checkbox:                      pulumi.String("checkbox_red"),
// 			HideIos:                       pulumi.Bool(true),
// 			Label:                         pulumi.String("Example App"),
// 			PasswordField:                 pulumi.String("txtbox-password"),
// 			RedirectUrl:                   pulumi.String("https://example.com/redirect_url"),
// 			SharedPassword:                pulumi.String("sharedpass"),
// 			SharedUsername:                pulumi.String("sharedusername"),
// 			Status:                        pulumi.String("ACTIVE"),
// 			Url:                           pulumi.String("https://example.com/login.html"),
// 			UserNameTemplate:              pulumi.String("user.firstName"),
// 			UserNameTemplateSuffix:        pulumi.String("hello"),
// 			UserNameTemplateType:          pulumi.String("CUSTOM"),
// 			UsernameField:                 pulumi.String("txtbox-username"),
// 		})
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
//
// ## Import
//
// Okta SWA Shared Credentials App can be imported via the Okta ID.
//
// ```sh
//  $ pulumi import okta:index/appSharedCredentials:AppSharedCredentials example <app id>
// ```
//
//  It's also possible to import app without groups or/and users. In this case ID may look like this
//
// ```sh
//  $ pulumi import okta:index/appSharedCredentials:AppSharedCredentials example <app id>/skip_users
// ```
//
// ```sh
//  $ pulumi import okta:index/appSharedCredentials:AppSharedCredentials example <app id>/skip_users/skip_groups
// ```
//
// ```sh
//  $ pulumi import okta:index/appSharedCredentials:AppSharedCredentials example <app id>/skip_groups
// ```
type AppSharedCredentials struct {
	pulumi.CustomResourceState

	// Custom error page URL.
	AccessibilityErrorRedirectUrl pulumi.StringPtrOutput `pulumi:"accessibilityErrorRedirectUrl"`
	// Custom login page for this application.
	AccessibilityLoginRedirectUrl pulumi.StringPtrOutput `pulumi:"accessibilityLoginRedirectUrl"`
	// Enable self-service. By default, it is `false`.
	AccessibilitySelfService pulumi.BoolPtrOutput `pulumi:"accessibilitySelfService"`
	// Application notes for admins.
	AdminNote pulumi.StringPtrOutput `pulumi:"adminNote"`
	// Displays specific appLinks for the app
	AppLinksJson pulumi.StringPtrOutput `pulumi:"appLinksJson"`
	// Display auto submit toolbar.
	AutoSubmitToolbar pulumi.BoolPtrOutput `pulumi:"autoSubmitToolbar"`
	// CSS selector for the Sign-In button in the sign-in form.
	ButtonField pulumi.StringPtrOutput `pulumi:"buttonField"`
	// CSS selector for the checkbox.
	Checkbox pulumi.StringPtrOutput `pulumi:"checkbox"`
	// Application notes for end users.
	EnduserNote pulumi.StringPtrOutput `pulumi:"enduserNote"`
	// Groups associated with the application
	//
	// Deprecated: The direct configuration of groups in this app resource is deprecated, please ensure you use the resource `okta_app_group_assignments` for this functionality.
	Groups pulumi.StringArrayOutput `pulumi:"groups"`
	// Do not display application icon on mobile app.
	HideIos pulumi.BoolPtrOutput `pulumi:"hideIos"`
	// Do not display application icon to users.
	HideWeb pulumi.BoolPtrOutput `pulumi:"hideWeb"`
	// The Application's display name.
	Label pulumi.StringOutput `pulumi:"label"`
	// Local file path to the logo. The file must be in PNG, JPG, or GIF format, and less than 1 MB in size.
	Logo pulumi.StringPtrOutput `pulumi:"logo"`
	// Direct link of application logo.
	LogoUrl pulumi.StringOutput `pulumi:"logoUrl"`
	// Name assigned to the application by Okta.
	Name pulumi.StringOutput `pulumi:"name"`
	// CSS selector for the Password field in the sign-in form.
	PasswordField pulumi.StringPtrOutput `pulumi:"passwordField"`
	// Redirect URL.
	RedirectUrl pulumi.StringPtrOutput `pulumi:"redirectUrl"`
	// Shared password, required for certain schemes.
	SharedPassword pulumi.StringPtrOutput `pulumi:"sharedPassword"`
	// Shared username, required for certain schemes.
	SharedUsername pulumi.StringPtrOutput `pulumi:"sharedUsername"`
	// Authentication mode of app.
	SignOnMode pulumi.StringOutput `pulumi:"signOnMode"`
	// Indicator that allows the app to skip `groups` sync (it's also can be provided during import). Default is `false`.
	SkipGroups pulumi.BoolPtrOutput `pulumi:"skipGroups"`
	// Indicator that allows the app to skip `users` sync (it's also can be provided during import). Default is `false`.
	SkipUsers pulumi.BoolPtrOutput `pulumi:"skipUsers"`
	// The status of the application, by default, it is `"ACTIVE"`.
	Status pulumi.StringPtrOutput `pulumi:"status"`
	// The URL of the sign-in page for this app.
	Url pulumi.StringPtrOutput `pulumi:"url"`
	// A regular expression that further restricts url to the specified regular expression.
	UrlRegex pulumi.StringPtrOutput `pulumi:"urlRegex"`
	// Username template. Default: `"${source.login}"`
	UserNameTemplate pulumi.StringPtrOutput `pulumi:"userNameTemplate"`
	// Username template suffix.
	UserNameTemplateSuffix pulumi.StringPtrOutput `pulumi:"userNameTemplateSuffix"`
	// Username template type. Default: `"BUILT_IN"`
	UserNameTemplateType pulumi.StringPtrOutput `pulumi:"userNameTemplateType"`
	// CSS selector for the username field.
	UsernameField pulumi.StringPtrOutput `pulumi:"usernameField"`
	// Users associated with the application
	//
	// Deprecated: The direct configuration of users in this app resource is deprecated, please ensure you use the resource `okta_app_user` for this functionality.
	Users AppSharedCredentialsUserArrayOutput `pulumi:"users"`
}

// NewAppSharedCredentials registers a new resource with the given unique name, arguments, and options.
func NewAppSharedCredentials(ctx *pulumi.Context,
	name string, args *AppSharedCredentialsArgs, opts ...pulumi.ResourceOption) (*AppSharedCredentials, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Label == nil {
		return nil, errors.New("invalid value for required argument 'Label'")
	}
	var resource AppSharedCredentials
	err := ctx.RegisterResource("okta:index/appSharedCredentials:AppSharedCredentials", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAppSharedCredentials gets an existing AppSharedCredentials resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAppSharedCredentials(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AppSharedCredentialsState, opts ...pulumi.ResourceOption) (*AppSharedCredentials, error) {
	var resource AppSharedCredentials
	err := ctx.ReadResource("okta:index/appSharedCredentials:AppSharedCredentials", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AppSharedCredentials resources.
type appSharedCredentialsState struct {
	// Custom error page URL.
	AccessibilityErrorRedirectUrl *string `pulumi:"accessibilityErrorRedirectUrl"`
	// Custom login page for this application.
	AccessibilityLoginRedirectUrl *string `pulumi:"accessibilityLoginRedirectUrl"`
	// Enable self-service. By default, it is `false`.
	AccessibilitySelfService *bool `pulumi:"accessibilitySelfService"`
	// Application notes for admins.
	AdminNote *string `pulumi:"adminNote"`
	// Displays specific appLinks for the app
	AppLinksJson *string `pulumi:"appLinksJson"`
	// Display auto submit toolbar.
	AutoSubmitToolbar *bool `pulumi:"autoSubmitToolbar"`
	// CSS selector for the Sign-In button in the sign-in form.
	ButtonField *string `pulumi:"buttonField"`
	// CSS selector for the checkbox.
	Checkbox *string `pulumi:"checkbox"`
	// Application notes for end users.
	EnduserNote *string `pulumi:"enduserNote"`
	// Groups associated with the application
	//
	// Deprecated: The direct configuration of groups in this app resource is deprecated, please ensure you use the resource `okta_app_group_assignments` for this functionality.
	Groups []string `pulumi:"groups"`
	// Do not display application icon on mobile app.
	HideIos *bool `pulumi:"hideIos"`
	// Do not display application icon to users.
	HideWeb *bool `pulumi:"hideWeb"`
	// The Application's display name.
	Label *string `pulumi:"label"`
	// Local file path to the logo. The file must be in PNG, JPG, or GIF format, and less than 1 MB in size.
	Logo *string `pulumi:"logo"`
	// Direct link of application logo.
	LogoUrl *string `pulumi:"logoUrl"`
	// Name assigned to the application by Okta.
	Name *string `pulumi:"name"`
	// CSS selector for the Password field in the sign-in form.
	PasswordField *string `pulumi:"passwordField"`
	// Redirect URL.
	RedirectUrl *string `pulumi:"redirectUrl"`
	// Shared password, required for certain schemes.
	SharedPassword *string `pulumi:"sharedPassword"`
	// Shared username, required for certain schemes.
	SharedUsername *string `pulumi:"sharedUsername"`
	// Authentication mode of app.
	SignOnMode *string `pulumi:"signOnMode"`
	// Indicator that allows the app to skip `groups` sync (it's also can be provided during import). Default is `false`.
	SkipGroups *bool `pulumi:"skipGroups"`
	// Indicator that allows the app to skip `users` sync (it's also can be provided during import). Default is `false`.
	SkipUsers *bool `pulumi:"skipUsers"`
	// The status of the application, by default, it is `"ACTIVE"`.
	Status *string `pulumi:"status"`
	// The URL of the sign-in page for this app.
	Url *string `pulumi:"url"`
	// A regular expression that further restricts url to the specified regular expression.
	UrlRegex *string `pulumi:"urlRegex"`
	// Username template. Default: `"${source.login}"`
	UserNameTemplate *string `pulumi:"userNameTemplate"`
	// Username template suffix.
	UserNameTemplateSuffix *string `pulumi:"userNameTemplateSuffix"`
	// Username template type. Default: `"BUILT_IN"`
	UserNameTemplateType *string `pulumi:"userNameTemplateType"`
	// CSS selector for the username field.
	UsernameField *string `pulumi:"usernameField"`
	// Users associated with the application
	//
	// Deprecated: The direct configuration of users in this app resource is deprecated, please ensure you use the resource `okta_app_user` for this functionality.
	Users []AppSharedCredentialsUser `pulumi:"users"`
}

type AppSharedCredentialsState struct {
	// Custom error page URL.
	AccessibilityErrorRedirectUrl pulumi.StringPtrInput
	// Custom login page for this application.
	AccessibilityLoginRedirectUrl pulumi.StringPtrInput
	// Enable self-service. By default, it is `false`.
	AccessibilitySelfService pulumi.BoolPtrInput
	// Application notes for admins.
	AdminNote pulumi.StringPtrInput
	// Displays specific appLinks for the app
	AppLinksJson pulumi.StringPtrInput
	// Display auto submit toolbar.
	AutoSubmitToolbar pulumi.BoolPtrInput
	// CSS selector for the Sign-In button in the sign-in form.
	ButtonField pulumi.StringPtrInput
	// CSS selector for the checkbox.
	Checkbox pulumi.StringPtrInput
	// Application notes for end users.
	EnduserNote pulumi.StringPtrInput
	// Groups associated with the application
	//
	// Deprecated: The direct configuration of groups in this app resource is deprecated, please ensure you use the resource `okta_app_group_assignments` for this functionality.
	Groups pulumi.StringArrayInput
	// Do not display application icon on mobile app.
	HideIos pulumi.BoolPtrInput
	// Do not display application icon to users.
	HideWeb pulumi.BoolPtrInput
	// The Application's display name.
	Label pulumi.StringPtrInput
	// Local file path to the logo. The file must be in PNG, JPG, or GIF format, and less than 1 MB in size.
	Logo pulumi.StringPtrInput
	// Direct link of application logo.
	LogoUrl pulumi.StringPtrInput
	// Name assigned to the application by Okta.
	Name pulumi.StringPtrInput
	// CSS selector for the Password field in the sign-in form.
	PasswordField pulumi.StringPtrInput
	// Redirect URL.
	RedirectUrl pulumi.StringPtrInput
	// Shared password, required for certain schemes.
	SharedPassword pulumi.StringPtrInput
	// Shared username, required for certain schemes.
	SharedUsername pulumi.StringPtrInput
	// Authentication mode of app.
	SignOnMode pulumi.StringPtrInput
	// Indicator that allows the app to skip `groups` sync (it's also can be provided during import). Default is `false`.
	SkipGroups pulumi.BoolPtrInput
	// Indicator that allows the app to skip `users` sync (it's also can be provided during import). Default is `false`.
	SkipUsers pulumi.BoolPtrInput
	// The status of the application, by default, it is `"ACTIVE"`.
	Status pulumi.StringPtrInput
	// The URL of the sign-in page for this app.
	Url pulumi.StringPtrInput
	// A regular expression that further restricts url to the specified regular expression.
	UrlRegex pulumi.StringPtrInput
	// Username template. Default: `"${source.login}"`
	UserNameTemplate pulumi.StringPtrInput
	// Username template suffix.
	UserNameTemplateSuffix pulumi.StringPtrInput
	// Username template type. Default: `"BUILT_IN"`
	UserNameTemplateType pulumi.StringPtrInput
	// CSS selector for the username field.
	UsernameField pulumi.StringPtrInput
	// Users associated with the application
	//
	// Deprecated: The direct configuration of users in this app resource is deprecated, please ensure you use the resource `okta_app_user` for this functionality.
	Users AppSharedCredentialsUserArrayInput
}

func (AppSharedCredentialsState) ElementType() reflect.Type {
	return reflect.TypeOf((*appSharedCredentialsState)(nil)).Elem()
}

type appSharedCredentialsArgs struct {
	// Custom error page URL.
	AccessibilityErrorRedirectUrl *string `pulumi:"accessibilityErrorRedirectUrl"`
	// Custom login page for this application.
	AccessibilityLoginRedirectUrl *string `pulumi:"accessibilityLoginRedirectUrl"`
	// Enable self-service. By default, it is `false`.
	AccessibilitySelfService *bool `pulumi:"accessibilitySelfService"`
	// Application notes for admins.
	AdminNote *string `pulumi:"adminNote"`
	// Displays specific appLinks for the app
	AppLinksJson *string `pulumi:"appLinksJson"`
	// Display auto submit toolbar.
	AutoSubmitToolbar *bool `pulumi:"autoSubmitToolbar"`
	// CSS selector for the Sign-In button in the sign-in form.
	ButtonField *string `pulumi:"buttonField"`
	// CSS selector for the checkbox.
	Checkbox *string `pulumi:"checkbox"`
	// Application notes for end users.
	EnduserNote *string `pulumi:"enduserNote"`
	// Groups associated with the application
	//
	// Deprecated: The direct configuration of groups in this app resource is deprecated, please ensure you use the resource `okta_app_group_assignments` for this functionality.
	Groups []string `pulumi:"groups"`
	// Do not display application icon on mobile app.
	HideIos *bool `pulumi:"hideIos"`
	// Do not display application icon to users.
	HideWeb *bool `pulumi:"hideWeb"`
	// The Application's display name.
	Label string `pulumi:"label"`
	// Local file path to the logo. The file must be in PNG, JPG, or GIF format, and less than 1 MB in size.
	Logo *string `pulumi:"logo"`
	// CSS selector for the Password field in the sign-in form.
	PasswordField *string `pulumi:"passwordField"`
	// Redirect URL.
	RedirectUrl *string `pulumi:"redirectUrl"`
	// Shared password, required for certain schemes.
	SharedPassword *string `pulumi:"sharedPassword"`
	// Shared username, required for certain schemes.
	SharedUsername *string `pulumi:"sharedUsername"`
	// Indicator that allows the app to skip `groups` sync (it's also can be provided during import). Default is `false`.
	SkipGroups *bool `pulumi:"skipGroups"`
	// Indicator that allows the app to skip `users` sync (it's also can be provided during import). Default is `false`.
	SkipUsers *bool `pulumi:"skipUsers"`
	// The status of the application, by default, it is `"ACTIVE"`.
	Status *string `pulumi:"status"`
	// The URL of the sign-in page for this app.
	Url *string `pulumi:"url"`
	// A regular expression that further restricts url to the specified regular expression.
	UrlRegex *string `pulumi:"urlRegex"`
	// Username template. Default: `"${source.login}"`
	UserNameTemplate *string `pulumi:"userNameTemplate"`
	// Username template suffix.
	UserNameTemplateSuffix *string `pulumi:"userNameTemplateSuffix"`
	// Username template type. Default: `"BUILT_IN"`
	UserNameTemplateType *string `pulumi:"userNameTemplateType"`
	// CSS selector for the username field.
	UsernameField *string `pulumi:"usernameField"`
	// Users associated with the application
	//
	// Deprecated: The direct configuration of users in this app resource is deprecated, please ensure you use the resource `okta_app_user` for this functionality.
	Users []AppSharedCredentialsUser `pulumi:"users"`
}

// The set of arguments for constructing a AppSharedCredentials resource.
type AppSharedCredentialsArgs struct {
	// Custom error page URL.
	AccessibilityErrorRedirectUrl pulumi.StringPtrInput
	// Custom login page for this application.
	AccessibilityLoginRedirectUrl pulumi.StringPtrInput
	// Enable self-service. By default, it is `false`.
	AccessibilitySelfService pulumi.BoolPtrInput
	// Application notes for admins.
	AdminNote pulumi.StringPtrInput
	// Displays specific appLinks for the app
	AppLinksJson pulumi.StringPtrInput
	// Display auto submit toolbar.
	AutoSubmitToolbar pulumi.BoolPtrInput
	// CSS selector for the Sign-In button in the sign-in form.
	ButtonField pulumi.StringPtrInput
	// CSS selector for the checkbox.
	Checkbox pulumi.StringPtrInput
	// Application notes for end users.
	EnduserNote pulumi.StringPtrInput
	// Groups associated with the application
	//
	// Deprecated: The direct configuration of groups in this app resource is deprecated, please ensure you use the resource `okta_app_group_assignments` for this functionality.
	Groups pulumi.StringArrayInput
	// Do not display application icon on mobile app.
	HideIos pulumi.BoolPtrInput
	// Do not display application icon to users.
	HideWeb pulumi.BoolPtrInput
	// The Application's display name.
	Label pulumi.StringInput
	// Local file path to the logo. The file must be in PNG, JPG, or GIF format, and less than 1 MB in size.
	Logo pulumi.StringPtrInput
	// CSS selector for the Password field in the sign-in form.
	PasswordField pulumi.StringPtrInput
	// Redirect URL.
	RedirectUrl pulumi.StringPtrInput
	// Shared password, required for certain schemes.
	SharedPassword pulumi.StringPtrInput
	// Shared username, required for certain schemes.
	SharedUsername pulumi.StringPtrInput
	// Indicator that allows the app to skip `groups` sync (it's also can be provided during import). Default is `false`.
	SkipGroups pulumi.BoolPtrInput
	// Indicator that allows the app to skip `users` sync (it's also can be provided during import). Default is `false`.
	SkipUsers pulumi.BoolPtrInput
	// The status of the application, by default, it is `"ACTIVE"`.
	Status pulumi.StringPtrInput
	// The URL of the sign-in page for this app.
	Url pulumi.StringPtrInput
	// A regular expression that further restricts url to the specified regular expression.
	UrlRegex pulumi.StringPtrInput
	// Username template. Default: `"${source.login}"`
	UserNameTemplate pulumi.StringPtrInput
	// Username template suffix.
	UserNameTemplateSuffix pulumi.StringPtrInput
	// Username template type. Default: `"BUILT_IN"`
	UserNameTemplateType pulumi.StringPtrInput
	// CSS selector for the username field.
	UsernameField pulumi.StringPtrInput
	// Users associated with the application
	//
	// Deprecated: The direct configuration of users in this app resource is deprecated, please ensure you use the resource `okta_app_user` for this functionality.
	Users AppSharedCredentialsUserArrayInput
}

func (AppSharedCredentialsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*appSharedCredentialsArgs)(nil)).Elem()
}

type AppSharedCredentialsInput interface {
	pulumi.Input

	ToAppSharedCredentialsOutput() AppSharedCredentialsOutput
	ToAppSharedCredentialsOutputWithContext(ctx context.Context) AppSharedCredentialsOutput
}

func (*AppSharedCredentials) ElementType() reflect.Type {
	return reflect.TypeOf((*AppSharedCredentials)(nil))
}

func (i *AppSharedCredentials) ToAppSharedCredentialsOutput() AppSharedCredentialsOutput {
	return i.ToAppSharedCredentialsOutputWithContext(context.Background())
}

func (i *AppSharedCredentials) ToAppSharedCredentialsOutputWithContext(ctx context.Context) AppSharedCredentialsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppSharedCredentialsOutput)
}

func (i *AppSharedCredentials) ToAppSharedCredentialsPtrOutput() AppSharedCredentialsPtrOutput {
	return i.ToAppSharedCredentialsPtrOutputWithContext(context.Background())
}

func (i *AppSharedCredentials) ToAppSharedCredentialsPtrOutputWithContext(ctx context.Context) AppSharedCredentialsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppSharedCredentialsPtrOutput)
}

type AppSharedCredentialsPtrInput interface {
	pulumi.Input

	ToAppSharedCredentialsPtrOutput() AppSharedCredentialsPtrOutput
	ToAppSharedCredentialsPtrOutputWithContext(ctx context.Context) AppSharedCredentialsPtrOutput
}

type appSharedCredentialsPtrType AppSharedCredentialsArgs

func (*appSharedCredentialsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AppSharedCredentials)(nil))
}

func (i *appSharedCredentialsPtrType) ToAppSharedCredentialsPtrOutput() AppSharedCredentialsPtrOutput {
	return i.ToAppSharedCredentialsPtrOutputWithContext(context.Background())
}

func (i *appSharedCredentialsPtrType) ToAppSharedCredentialsPtrOutputWithContext(ctx context.Context) AppSharedCredentialsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppSharedCredentialsPtrOutput)
}

// AppSharedCredentialsArrayInput is an input type that accepts AppSharedCredentialsArray and AppSharedCredentialsArrayOutput values.
// You can construct a concrete instance of `AppSharedCredentialsArrayInput` via:
//
//          AppSharedCredentialsArray{ AppSharedCredentialsArgs{...} }
type AppSharedCredentialsArrayInput interface {
	pulumi.Input

	ToAppSharedCredentialsArrayOutput() AppSharedCredentialsArrayOutput
	ToAppSharedCredentialsArrayOutputWithContext(context.Context) AppSharedCredentialsArrayOutput
}

type AppSharedCredentialsArray []AppSharedCredentialsInput

func (AppSharedCredentialsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*AppSharedCredentials)(nil)).Elem()
}

func (i AppSharedCredentialsArray) ToAppSharedCredentialsArrayOutput() AppSharedCredentialsArrayOutput {
	return i.ToAppSharedCredentialsArrayOutputWithContext(context.Background())
}

func (i AppSharedCredentialsArray) ToAppSharedCredentialsArrayOutputWithContext(ctx context.Context) AppSharedCredentialsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppSharedCredentialsArrayOutput)
}

// AppSharedCredentialsMapInput is an input type that accepts AppSharedCredentialsMap and AppSharedCredentialsMapOutput values.
// You can construct a concrete instance of `AppSharedCredentialsMapInput` via:
//
//          AppSharedCredentialsMap{ "key": AppSharedCredentialsArgs{...} }
type AppSharedCredentialsMapInput interface {
	pulumi.Input

	ToAppSharedCredentialsMapOutput() AppSharedCredentialsMapOutput
	ToAppSharedCredentialsMapOutputWithContext(context.Context) AppSharedCredentialsMapOutput
}

type AppSharedCredentialsMap map[string]AppSharedCredentialsInput

func (AppSharedCredentialsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*AppSharedCredentials)(nil)).Elem()
}

func (i AppSharedCredentialsMap) ToAppSharedCredentialsMapOutput() AppSharedCredentialsMapOutput {
	return i.ToAppSharedCredentialsMapOutputWithContext(context.Background())
}

func (i AppSharedCredentialsMap) ToAppSharedCredentialsMapOutputWithContext(ctx context.Context) AppSharedCredentialsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppSharedCredentialsMapOutput)
}

type AppSharedCredentialsOutput struct{ *pulumi.OutputState }

func (AppSharedCredentialsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AppSharedCredentials)(nil))
}

func (o AppSharedCredentialsOutput) ToAppSharedCredentialsOutput() AppSharedCredentialsOutput {
	return o
}

func (o AppSharedCredentialsOutput) ToAppSharedCredentialsOutputWithContext(ctx context.Context) AppSharedCredentialsOutput {
	return o
}

func (o AppSharedCredentialsOutput) ToAppSharedCredentialsPtrOutput() AppSharedCredentialsPtrOutput {
	return o.ToAppSharedCredentialsPtrOutputWithContext(context.Background())
}

func (o AppSharedCredentialsOutput) ToAppSharedCredentialsPtrOutputWithContext(ctx context.Context) AppSharedCredentialsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AppSharedCredentials) *AppSharedCredentials {
		return &v
	}).(AppSharedCredentialsPtrOutput)
}

type AppSharedCredentialsPtrOutput struct{ *pulumi.OutputState }

func (AppSharedCredentialsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AppSharedCredentials)(nil))
}

func (o AppSharedCredentialsPtrOutput) ToAppSharedCredentialsPtrOutput() AppSharedCredentialsPtrOutput {
	return o
}

func (o AppSharedCredentialsPtrOutput) ToAppSharedCredentialsPtrOutputWithContext(ctx context.Context) AppSharedCredentialsPtrOutput {
	return o
}

func (o AppSharedCredentialsPtrOutput) Elem() AppSharedCredentialsOutput {
	return o.ApplyT(func(v *AppSharedCredentials) AppSharedCredentials {
		if v != nil {
			return *v
		}
		var ret AppSharedCredentials
		return ret
	}).(AppSharedCredentialsOutput)
}

type AppSharedCredentialsArrayOutput struct{ *pulumi.OutputState }

func (AppSharedCredentialsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AppSharedCredentials)(nil))
}

func (o AppSharedCredentialsArrayOutput) ToAppSharedCredentialsArrayOutput() AppSharedCredentialsArrayOutput {
	return o
}

func (o AppSharedCredentialsArrayOutput) ToAppSharedCredentialsArrayOutputWithContext(ctx context.Context) AppSharedCredentialsArrayOutput {
	return o
}

func (o AppSharedCredentialsArrayOutput) Index(i pulumi.IntInput) AppSharedCredentialsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AppSharedCredentials {
		return vs[0].([]AppSharedCredentials)[vs[1].(int)]
	}).(AppSharedCredentialsOutput)
}

type AppSharedCredentialsMapOutput struct{ *pulumi.OutputState }

func (AppSharedCredentialsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]AppSharedCredentials)(nil))
}

func (o AppSharedCredentialsMapOutput) ToAppSharedCredentialsMapOutput() AppSharedCredentialsMapOutput {
	return o
}

func (o AppSharedCredentialsMapOutput) ToAppSharedCredentialsMapOutputWithContext(ctx context.Context) AppSharedCredentialsMapOutput {
	return o
}

func (o AppSharedCredentialsMapOutput) MapIndex(k pulumi.StringInput) AppSharedCredentialsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) AppSharedCredentials {
		return vs[0].(map[string]AppSharedCredentials)[vs[1].(string)]
	}).(AppSharedCredentialsOutput)
}

func init() {
	pulumi.RegisterOutputType(AppSharedCredentialsOutput{})
	pulumi.RegisterOutputType(AppSharedCredentialsPtrOutput{})
	pulumi.RegisterOutputType(AppSharedCredentialsArrayOutput{})
	pulumi.RegisterOutputType(AppSharedCredentialsMapOutput{})
}
