// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package okta

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-okta/sdk/v6/go/okta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Security Events Provider instance for signal ingestion.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-okta/sdk/v6/go/okta"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := okta.LookupSecurityEventsProvider(ctx, &okta.LookupSecurityEventsProviderArgs{
//				Id: "<security_events_provider_id>",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSecurityEventsProvider(ctx *pulumi.Context, args *LookupSecurityEventsProviderArgs, opts ...pulumi.InvokeOption) (*LookupSecurityEventsProviderResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSecurityEventsProviderResult
	err := ctx.Invoke("okta:index/getSecurityEventsProvider:getSecurityEventsProvider", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSecurityEventsProvider.
type LookupSecurityEventsProviderArgs struct {
	// The unique identifier of this instance.
	Id       string                             `pulumi:"id"`
	Settings *GetSecurityEventsProviderSettings `pulumi:"settings"`
}

// A collection of values returned by getSecurityEventsProvider.
type LookupSecurityEventsProviderResult struct {
	// The unique identifier of this instance.
	Id string `pulumi:"id"`
	// Whether or not the Security Events Provider is enabled.
	IsEnabled string `pulumi:"isEnabled"`
	// The name of the Security Events Provider instance.
	Name     string                             `pulumi:"name"`
	Settings *GetSecurityEventsProviderSettings `pulumi:"settings"`
	// Indicates whether the Security Events Provider is active or not.
	Status string `pulumi:"status"`
	// The application type of the Security Events Provider.
	Type string `pulumi:"type"`
}

func LookupSecurityEventsProviderOutput(ctx *pulumi.Context, args LookupSecurityEventsProviderOutputArgs, opts ...pulumi.InvokeOption) LookupSecurityEventsProviderResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSecurityEventsProviderResultOutput, error) {
			args := v.(LookupSecurityEventsProviderArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("okta:index/getSecurityEventsProvider:getSecurityEventsProvider", args, LookupSecurityEventsProviderResultOutput{}, options).(LookupSecurityEventsProviderResultOutput), nil
		}).(LookupSecurityEventsProviderResultOutput)
}

// A collection of arguments for invoking getSecurityEventsProvider.
type LookupSecurityEventsProviderOutputArgs struct {
	// The unique identifier of this instance.
	Id       pulumi.StringInput                        `pulumi:"id"`
	Settings GetSecurityEventsProviderSettingsPtrInput `pulumi:"settings"`
}

func (LookupSecurityEventsProviderOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecurityEventsProviderArgs)(nil)).Elem()
}

// A collection of values returned by getSecurityEventsProvider.
type LookupSecurityEventsProviderResultOutput struct{ *pulumi.OutputState }

func (LookupSecurityEventsProviderResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecurityEventsProviderResult)(nil)).Elem()
}

func (o LookupSecurityEventsProviderResultOutput) ToLookupSecurityEventsProviderResultOutput() LookupSecurityEventsProviderResultOutput {
	return o
}

func (o LookupSecurityEventsProviderResultOutput) ToLookupSecurityEventsProviderResultOutputWithContext(ctx context.Context) LookupSecurityEventsProviderResultOutput {
	return o
}

// The unique identifier of this instance.
func (o LookupSecurityEventsProviderResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityEventsProviderResult) string { return v.Id }).(pulumi.StringOutput)
}

// Whether or not the Security Events Provider is enabled.
func (o LookupSecurityEventsProviderResultOutput) IsEnabled() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityEventsProviderResult) string { return v.IsEnabled }).(pulumi.StringOutput)
}

// The name of the Security Events Provider instance.
func (o LookupSecurityEventsProviderResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityEventsProviderResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSecurityEventsProviderResultOutput) Settings() GetSecurityEventsProviderSettingsPtrOutput {
	return o.ApplyT(func(v LookupSecurityEventsProviderResult) *GetSecurityEventsProviderSettings { return v.Settings }).(GetSecurityEventsProviderSettingsPtrOutput)
}

// Indicates whether the Security Events Provider is active or not.
func (o LookupSecurityEventsProviderResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityEventsProviderResult) string { return v.Status }).(pulumi.StringOutput)
}

// The application type of the Security Events Provider.
func (o LookupSecurityEventsProviderResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSecurityEventsProviderResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSecurityEventsProviderResultOutput{})
}
