// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package okta

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-okta/sdk/v4/go/okta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get the email templates belonging to a brand in an Okta organization.
func GetTemplates(ctx *pulumi.Context, args *GetTemplatesArgs, opts ...pulumi.InvokeOption) (*GetTemplatesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTemplatesResult
	err := ctx.Invoke("okta:index/getTemplates:getTemplates", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTemplates.
type GetTemplatesArgs struct {
	// Brand ID
	BrandId string `pulumi:"brandId"`
}

// A collection of values returned by getTemplates.
type GetTemplatesResult struct {
	// Brand ID
	BrandId string `pulumi:"brandId"`
	// List of `getTemplate` belonging to a brand in the organization
	EmailTemplates []GetTemplatesEmailTemplate `pulumi:"emailTemplates"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetTemplatesOutput(ctx *pulumi.Context, args GetTemplatesOutputArgs, opts ...pulumi.InvokeOption) GetTemplatesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetTemplatesResult, error) {
			args := v.(GetTemplatesArgs)
			r, err := GetTemplates(ctx, &args, opts...)
			var s GetTemplatesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetTemplatesResultOutput)
}

// A collection of arguments for invoking getTemplates.
type GetTemplatesOutputArgs struct {
	// Brand ID
	BrandId pulumi.StringInput `pulumi:"brandId"`
}

func (GetTemplatesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTemplatesArgs)(nil)).Elem()
}

// A collection of values returned by getTemplates.
type GetTemplatesResultOutput struct{ *pulumi.OutputState }

func (GetTemplatesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTemplatesResult)(nil)).Elem()
}

func (o GetTemplatesResultOutput) ToGetTemplatesResultOutput() GetTemplatesResultOutput {
	return o
}

func (o GetTemplatesResultOutput) ToGetTemplatesResultOutputWithContext(ctx context.Context) GetTemplatesResultOutput {
	return o
}

// Brand ID
func (o GetTemplatesResultOutput) BrandId() pulumi.StringOutput {
	return o.ApplyT(func(v GetTemplatesResult) string { return v.BrandId }).(pulumi.StringOutput)
}

// List of `getTemplate` belonging to a brand in the organization
func (o GetTemplatesResultOutput) EmailTemplates() GetTemplatesEmailTemplateArrayOutput {
	return o.ApplyT(func(v GetTemplatesResult) []GetTemplatesEmailTemplate { return v.EmailTemplates }).(GetTemplatesEmailTemplateArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetTemplatesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTemplatesResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTemplatesResultOutput{})
}
