// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package okta

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-okta/sdk/v6/go/okta/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The Client Role Assignments APIs allow you to assign roles and designate third-party admin status to public client apps.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-okta/sdk/v6/go/okta"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := okta.NewOauth2V1ClientsRoleApiAccessManagementAdmin(ctx, "example", &okta.Oauth2V1ClientsRoleApiAccessManagementAdminArgs{
//				ClientId: pulumi.String("<client_id>"),
//				Type:     pulumi.String("API_ACCESS_MANAGEMENT_ADMIN"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import okta:index/oauth2V1ClientsRoleApiAccessManagementAdmin:Oauth2V1ClientsRoleApiAccessManagementAdmin example <client_id>/<id>
// ```
type Oauth2V1ClientsRoleApiAccessManagementAdmin struct {
	pulumi.CustomResourceState

	// Role assignment type
	AssignmentType pulumi.StringOutput `pulumi:"assignmentType"`
	// `clientId` of the app
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// Timestamp when the object was created
	Created pulumi.StringOutput `pulumi:"created"`
	// Label for the role assignment
	Label pulumi.StringOutput `pulumi:"label"`
	// Timestamp when the object was last updated
	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	// Status of the role assignment
	Status pulumi.StringOutput `pulumi:"status"`
	// Discriminator field identifying the variant type. Must be set to "API*ACCESS*MANAGEMENT_ADMIN".
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewOauth2V1ClientsRoleApiAccessManagementAdmin registers a new resource with the given unique name, arguments, and options.
func NewOauth2V1ClientsRoleApiAccessManagementAdmin(ctx *pulumi.Context,
	name string, args *Oauth2V1ClientsRoleApiAccessManagementAdminArgs, opts ...pulumi.ResourceOption) (*Oauth2V1ClientsRoleApiAccessManagementAdmin, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Oauth2V1ClientsRoleApiAccessManagementAdmin
	err := ctx.RegisterResource("okta:index/oauth2V1ClientsRoleApiAccessManagementAdmin:Oauth2V1ClientsRoleApiAccessManagementAdmin", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOauth2V1ClientsRoleApiAccessManagementAdmin gets an existing Oauth2V1ClientsRoleApiAccessManagementAdmin resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOauth2V1ClientsRoleApiAccessManagementAdmin(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *Oauth2V1ClientsRoleApiAccessManagementAdminState, opts ...pulumi.ResourceOption) (*Oauth2V1ClientsRoleApiAccessManagementAdmin, error) {
	var resource Oauth2V1ClientsRoleApiAccessManagementAdmin
	err := ctx.ReadResource("okta:index/oauth2V1ClientsRoleApiAccessManagementAdmin:Oauth2V1ClientsRoleApiAccessManagementAdmin", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Oauth2V1ClientsRoleApiAccessManagementAdmin resources.
type oauth2V1ClientsRoleApiAccessManagementAdminState struct {
	// Role assignment type
	AssignmentType *string `pulumi:"assignmentType"`
	// `clientId` of the app
	ClientId *string `pulumi:"clientId"`
	// Timestamp when the object was created
	Created *string `pulumi:"created"`
	// Label for the role assignment
	Label *string `pulumi:"label"`
	// Timestamp when the object was last updated
	LastUpdated *string `pulumi:"lastUpdated"`
	// Status of the role assignment
	Status *string `pulumi:"status"`
	// Discriminator field identifying the variant type. Must be set to "API*ACCESS*MANAGEMENT_ADMIN".
	Type *string `pulumi:"type"`
}

type Oauth2V1ClientsRoleApiAccessManagementAdminState struct {
	// Role assignment type
	AssignmentType pulumi.StringPtrInput
	// `clientId` of the app
	ClientId pulumi.StringPtrInput
	// Timestamp when the object was created
	Created pulumi.StringPtrInput
	// Label for the role assignment
	Label pulumi.StringPtrInput
	// Timestamp when the object was last updated
	LastUpdated pulumi.StringPtrInput
	// Status of the role assignment
	Status pulumi.StringPtrInput
	// Discriminator field identifying the variant type. Must be set to "API*ACCESS*MANAGEMENT_ADMIN".
	Type pulumi.StringPtrInput
}

func (Oauth2V1ClientsRoleApiAccessManagementAdminState) ElementType() reflect.Type {
	return reflect.TypeOf((*oauth2V1ClientsRoleApiAccessManagementAdminState)(nil)).Elem()
}

type oauth2V1ClientsRoleApiAccessManagementAdminArgs struct {
	// Role assignment type
	AssignmentType *string `pulumi:"assignmentType"`
	// `clientId` of the app
	ClientId string `pulumi:"clientId"`
	// Status of the role assignment
	Status *string `pulumi:"status"`
	// Discriminator field identifying the variant type. Must be set to "API*ACCESS*MANAGEMENT_ADMIN".
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a Oauth2V1ClientsRoleApiAccessManagementAdmin resource.
type Oauth2V1ClientsRoleApiAccessManagementAdminArgs struct {
	// Role assignment type
	AssignmentType pulumi.StringPtrInput
	// `clientId` of the app
	ClientId pulumi.StringInput
	// Status of the role assignment
	Status pulumi.StringPtrInput
	// Discriminator field identifying the variant type. Must be set to "API*ACCESS*MANAGEMENT_ADMIN".
	Type pulumi.StringInput
}

func (Oauth2V1ClientsRoleApiAccessManagementAdminArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*oauth2V1ClientsRoleApiAccessManagementAdminArgs)(nil)).Elem()
}

type Oauth2V1ClientsRoleApiAccessManagementAdminInput interface {
	pulumi.Input

	ToOauth2V1ClientsRoleApiAccessManagementAdminOutput() Oauth2V1ClientsRoleApiAccessManagementAdminOutput
	ToOauth2V1ClientsRoleApiAccessManagementAdminOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminOutput
}

func (*Oauth2V1ClientsRoleApiAccessManagementAdmin) ElementType() reflect.Type {
	return reflect.TypeOf((**Oauth2V1ClientsRoleApiAccessManagementAdmin)(nil)).Elem()
}

func (i *Oauth2V1ClientsRoleApiAccessManagementAdmin) ToOauth2V1ClientsRoleApiAccessManagementAdminOutput() Oauth2V1ClientsRoleApiAccessManagementAdminOutput {
	return i.ToOauth2V1ClientsRoleApiAccessManagementAdminOutputWithContext(context.Background())
}

func (i *Oauth2V1ClientsRoleApiAccessManagementAdmin) ToOauth2V1ClientsRoleApiAccessManagementAdminOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Oauth2V1ClientsRoleApiAccessManagementAdminOutput)
}

// Oauth2V1ClientsRoleApiAccessManagementAdminArrayInput is an input type that accepts Oauth2V1ClientsRoleApiAccessManagementAdminArray and Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput values.
// You can construct a concrete instance of `Oauth2V1ClientsRoleApiAccessManagementAdminArrayInput` via:
//
//	Oauth2V1ClientsRoleApiAccessManagementAdminArray{ Oauth2V1ClientsRoleApiAccessManagementAdminArgs{...} }
type Oauth2V1ClientsRoleApiAccessManagementAdminArrayInput interface {
	pulumi.Input

	ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutput() Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput
	ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutputWithContext(context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput
}

type Oauth2V1ClientsRoleApiAccessManagementAdminArray []Oauth2V1ClientsRoleApiAccessManagementAdminInput

func (Oauth2V1ClientsRoleApiAccessManagementAdminArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Oauth2V1ClientsRoleApiAccessManagementAdmin)(nil)).Elem()
}

func (i Oauth2V1ClientsRoleApiAccessManagementAdminArray) ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutput() Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput {
	return i.ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutputWithContext(context.Background())
}

func (i Oauth2V1ClientsRoleApiAccessManagementAdminArray) ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput)
}

// Oauth2V1ClientsRoleApiAccessManagementAdminMapInput is an input type that accepts Oauth2V1ClientsRoleApiAccessManagementAdminMap and Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput values.
// You can construct a concrete instance of `Oauth2V1ClientsRoleApiAccessManagementAdminMapInput` via:
//
//	Oauth2V1ClientsRoleApiAccessManagementAdminMap{ "key": Oauth2V1ClientsRoleApiAccessManagementAdminArgs{...} }
type Oauth2V1ClientsRoleApiAccessManagementAdminMapInput interface {
	pulumi.Input

	ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutput() Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput
	ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutputWithContext(context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput
}

type Oauth2V1ClientsRoleApiAccessManagementAdminMap map[string]Oauth2V1ClientsRoleApiAccessManagementAdminInput

func (Oauth2V1ClientsRoleApiAccessManagementAdminMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Oauth2V1ClientsRoleApiAccessManagementAdmin)(nil)).Elem()
}

func (i Oauth2V1ClientsRoleApiAccessManagementAdminMap) ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutput() Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput {
	return i.ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutputWithContext(context.Background())
}

func (i Oauth2V1ClientsRoleApiAccessManagementAdminMap) ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput)
}

type Oauth2V1ClientsRoleApiAccessManagementAdminOutput struct{ *pulumi.OutputState }

func (Oauth2V1ClientsRoleApiAccessManagementAdminOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Oauth2V1ClientsRoleApiAccessManagementAdmin)(nil)).Elem()
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) ToOauth2V1ClientsRoleApiAccessManagementAdminOutput() Oauth2V1ClientsRoleApiAccessManagementAdminOutput {
	return o
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) ToOauth2V1ClientsRoleApiAccessManagementAdminOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminOutput {
	return o
}

// Role assignment type
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) AssignmentType() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.AssignmentType }).(pulumi.StringOutput)
}

// `clientId` of the app
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// Timestamp when the object was created
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// Label for the role assignment
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.Label }).(pulumi.StringOutput)
}

// Timestamp when the object was last updated
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// Status of the role assignment
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// Discriminator field identifying the variant type. Must be set to "API*ACCESS*MANAGEMENT_ADMIN".
func (o Oauth2V1ClientsRoleApiAccessManagementAdminOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Oauth2V1ClientsRoleApiAccessManagementAdmin) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput struct{ *pulumi.OutputState }

func (Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Oauth2V1ClientsRoleApiAccessManagementAdmin)(nil)).Elem()
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput) ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutput() Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput {
	return o
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput) ToOauth2V1ClientsRoleApiAccessManagementAdminArrayOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput {
	return o
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput) Index(i pulumi.IntInput) Oauth2V1ClientsRoleApiAccessManagementAdminOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Oauth2V1ClientsRoleApiAccessManagementAdmin {
		return vs[0].([]*Oauth2V1ClientsRoleApiAccessManagementAdmin)[vs[1].(int)]
	}).(Oauth2V1ClientsRoleApiAccessManagementAdminOutput)
}

type Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput struct{ *pulumi.OutputState }

func (Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Oauth2V1ClientsRoleApiAccessManagementAdmin)(nil)).Elem()
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput) ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutput() Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput {
	return o
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput) ToOauth2V1ClientsRoleApiAccessManagementAdminMapOutputWithContext(ctx context.Context) Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput {
	return o
}

func (o Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput) MapIndex(k pulumi.StringInput) Oauth2V1ClientsRoleApiAccessManagementAdminOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Oauth2V1ClientsRoleApiAccessManagementAdmin {
		return vs[0].(map[string]*Oauth2V1ClientsRoleApiAccessManagementAdmin)[vs[1].(string)]
	}).(Oauth2V1ClientsRoleApiAccessManagementAdminOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*Oauth2V1ClientsRoleApiAccessManagementAdminInput)(nil)).Elem(), &Oauth2V1ClientsRoleApiAccessManagementAdmin{})
	pulumi.RegisterInputType(reflect.TypeOf((*Oauth2V1ClientsRoleApiAccessManagementAdminArrayInput)(nil)).Elem(), Oauth2V1ClientsRoleApiAccessManagementAdminArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Oauth2V1ClientsRoleApiAccessManagementAdminMapInput)(nil)).Elem(), Oauth2V1ClientsRoleApiAccessManagementAdminMap{})
	pulumi.RegisterOutputType(Oauth2V1ClientsRoleApiAccessManagementAdminOutput{})
	pulumi.RegisterOutputType(Oauth2V1ClientsRoleApiAccessManagementAdminArrayOutput{})
	pulumi.RegisterOutputType(Oauth2V1ClientsRoleApiAccessManagementAdminMapOutput{})
}
