// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.idp;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.okta.Utilities;
import com.pulumi.okta.idp.OidcArgs;
import com.pulumi.okta.idp.inputs.OidcState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="okta:idp/oidc:Oidc")
public class Oidc extends com.pulumi.resources.CustomResource {
    @Export(name="accountLinkAction", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accountLinkAction;

    public Output<Optional<String>> accountLinkAction() {
        return Codegen.optional(this.accountLinkAction);
    }
    @Export(name="accountLinkGroupIncludes", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> accountLinkGroupIncludes;

    public Output<Optional<List<String>>> accountLinkGroupIncludes() {
        return Codegen.optional(this.accountLinkGroupIncludes);
    }
    @Export(name="authorizationBinding", refs={String.class}, tree="[0]")
    private Output<String> authorizationBinding;

    public Output<String> authorizationBinding() {
        return this.authorizationBinding;
    }
    @Export(name="authorizationUrl", refs={String.class}, tree="[0]")
    private Output<String> authorizationUrl;

    public Output<String> authorizationUrl() {
        return this.authorizationUrl;
    }
    @Export(name="clientId", refs={String.class}, tree="[0]")
    private Output<String> clientId;

    public Output<String> clientId() {
        return this.clientId;
    }
    @Export(name="clientSecret", refs={String.class}, tree="[0]")
    private Output<String> clientSecret;

    public Output<String> clientSecret() {
        return this.clientSecret;
    }
    @Export(name="deprovisionedAction", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> deprovisionedAction;

    public Output<Optional<String>> deprovisionedAction() {
        return Codegen.optional(this.deprovisionedAction);
    }
    @Export(name="groupsAction", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> groupsAction;

    public Output<Optional<String>> groupsAction() {
        return Codegen.optional(this.groupsAction);
    }
    @Export(name="groupsAssignments", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> groupsAssignments;

    public Output<Optional<List<String>>> groupsAssignments() {
        return Codegen.optional(this.groupsAssignments);
    }
    @Export(name="groupsAttribute", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> groupsAttribute;

    public Output<Optional<String>> groupsAttribute() {
        return Codegen.optional(this.groupsAttribute);
    }
    @Export(name="groupsFilters", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> groupsFilters;

    public Output<Optional<List<String>>> groupsFilters() {
        return Codegen.optional(this.groupsFilters);
    }
    /**
     * Indicates whether Okta uses the original Okta org domain URL, custom domain URL, or dynamic. See Identity Provider attributes - issuerMode - https://developer.okta.com/docs/reference/api/idps/#identity-provider-attributes
     * 
     */
    @Export(name="issuerMode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> issuerMode;

    /**
     * @return Indicates whether Okta uses the original Okta org domain URL, custom domain URL, or dynamic. See Identity Provider attributes - issuerMode - https://developer.okta.com/docs/reference/api/idps/#identity-provider-attributes
     * 
     */
    public Output<Optional<String>> issuerMode() {
        return Codegen.optional(this.issuerMode);
    }
    @Export(name="issuerUrl", refs={String.class}, tree="[0]")
    private Output<String> issuerUrl;

    public Output<String> issuerUrl() {
        return this.issuerUrl;
    }
    @Export(name="jwksBinding", refs={String.class}, tree="[0]")
    private Output<String> jwksBinding;

    public Output<String> jwksBinding() {
        return this.jwksBinding;
    }
    @Export(name="jwksUrl", refs={String.class}, tree="[0]")
    private Output<String> jwksUrl;

    public Output<String> jwksUrl() {
        return this.jwksUrl;
    }
    @Export(name="maxClockSkew", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> maxClockSkew;

    public Output<Optional<Integer>> maxClockSkew() {
        return Codegen.optional(this.maxClockSkew);
    }
    /**
     * Name of the IdP
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Name of the IdP
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    @Export(name="profileMaster", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> profileMaster;

    public Output<Optional<Boolean>> profileMaster() {
        return Codegen.optional(this.profileMaster);
    }
    @Export(name="protocolType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> protocolType;

    public Output<Optional<String>> protocolType() {
        return Codegen.optional(this.protocolType);
    }
    @Export(name="provisioningAction", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> provisioningAction;

    public Output<Optional<String>> provisioningAction() {
        return Codegen.optional(this.provisioningAction);
    }
    /**
     * The HMAC Signature Algorithm used when signing an authorization request
     * 
     */
    @Export(name="requestSignatureAlgorithm", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> requestSignatureAlgorithm;

    /**
     * @return The HMAC Signature Algorithm used when signing an authorization request
     * 
     */
    public Output<Optional<String>> requestSignatureAlgorithm() {
        return Codegen.optional(this.requestSignatureAlgorithm);
    }
    /**
     * Specifies whether to digitally sign an authorization request to the IdP
     * 
     */
    @Export(name="requestSignatureScope", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> requestSignatureScope;

    /**
     * @return Specifies whether to digitally sign an authorization request to the IdP
     * 
     */
    public Output<Optional<String>> requestSignatureScope() {
        return Codegen.optional(this.requestSignatureScope);
    }
    @Export(name="scopes", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> scopes;

    public Output<List<String>> scopes() {
        return this.scopes;
    }
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> status;

    public Output<Optional<String>> status() {
        return Codegen.optional(this.status);
    }
    @Export(name="subjectMatchAttribute", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> subjectMatchAttribute;

    public Output<Optional<String>> subjectMatchAttribute() {
        return Codegen.optional(this.subjectMatchAttribute);
    }
    @Export(name="subjectMatchType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> subjectMatchType;

    public Output<Optional<String>> subjectMatchType() {
        return Codegen.optional(this.subjectMatchType);
    }
    @Export(name="suspendedAction", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> suspendedAction;

    public Output<Optional<String>> suspendedAction() {
        return Codegen.optional(this.suspendedAction);
    }
    @Export(name="tokenBinding", refs={String.class}, tree="[0]")
    private Output<String> tokenBinding;

    public Output<String> tokenBinding() {
        return this.tokenBinding;
    }
    @Export(name="tokenUrl", refs={String.class}, tree="[0]")
    private Output<String> tokenUrl;

    public Output<String> tokenUrl() {
        return this.tokenUrl;
    }
    /**
     * Type of OIDC IdP.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return Type of OIDC IdP.
     * 
     */
    public Output<String> type() {
        return this.type;
    }
    @Export(name="userInfoBinding", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userInfoBinding;

    public Output<Optional<String>> userInfoBinding() {
        return Codegen.optional(this.userInfoBinding);
    }
    @Export(name="userInfoUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userInfoUrl;

    public Output<Optional<String>> userInfoUrl() {
        return Codegen.optional(this.userInfoUrl);
    }
    @Export(name="userTypeId", refs={String.class}, tree="[0]")
    private Output<String> userTypeId;

    public Output<String> userTypeId() {
        return this.userTypeId;
    }
    @Export(name="usernameTemplate", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> usernameTemplate;

    public Output<Optional<String>> usernameTemplate() {
        return Codegen.optional(this.usernameTemplate);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Oidc(String name) {
        this(name, OidcArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Oidc(String name, OidcArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Oidc(String name, OidcArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("okta:idp/oidc:Oidc", name, args == null ? OidcArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private Oidc(String name, Output<String> id, @Nullable OidcState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("okta:idp/oidc:Oidc", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "clientSecret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Oidc get(String name, Output<String> id, @Nullable OidcState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Oidc(name, id, state, options);
    }
}
