// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.App.Inputs
{

    public sealed class GetSignOnPolicyRuleActionsAppSignOnVerificationMethodInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Verification method type
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public GetSignOnPolicyRuleActionsAppSignOnVerificationMethodInputArgs()
        {
        }
        public static new GetSignOnPolicyRuleActionsAppSignOnVerificationMethodInputArgs Empty => new GetSignOnPolicyRuleActionsAppSignOnVerificationMethodInputArgs();
    }
}
