// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.App.Inputs
{

    public sealed class SignonPolicyRulesRuleKeepMeSignedInGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the post-authentication KMSI flow is allowed. Valid values: `ALLOWED`, `NOT_ALLOWED`.
        /// </summary>
        [Input("postAuth")]
        public Input<string>? PostAuth { get; set; }

        /// <summary>
        /// How often the post-auth prompt is presented, as an ISO-8601 duration (e.g. `PT168H`).
        /// </summary>
        [Input("postAuthPromptFrequency")]
        public Input<string>? PostAuthPromptFrequency { get; set; }

        public SignonPolicyRulesRuleKeepMeSignedInGetArgs()
        {
        }
        public static new SignonPolicyRulesRuleKeepMeSignedInGetArgs Empty => new SignonPolicyRulesRuleKeepMeSignedInGetArgs();
    }
}
