// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AgentPoolUpdateScheduleArgs extends com.pulumi.resources.ResourceArgs {

    public static final AgentPoolUpdateScheduleArgs Empty = new AgentPoolUpdateScheduleArgs();

    /**
     * The schedule of the update in cron format.
     * 
     */
    @Import(name="cron")
    private @Nullable Output<String> cron;

    /**
     * @return The schedule of the update in cron format.
     * 
     */
    public Optional<Output<String>> cron() {
        return Optional.ofNullable(this.cron);
    }

    /**
     * Delay in days.
     * 
     */
    @Import(name="delay")
    private @Nullable Output<Integer> delay;

    /**
     * @return Delay in days.
     * 
     */
    public Optional<Output<Integer>> delay() {
        return Optional.ofNullable(this.delay);
    }

    /**
     * Duration in minutes.
     * 
     */
    @Import(name="duration")
    private @Nullable Output<Integer> duration;

    /**
     * @return Duration in minutes.
     * 
     */
    public Optional<Output<Integer>> duration() {
        return Optional.ofNullable(this.duration);
    }

    /**
     * Timestamp when the update finished (only for a successful or failed update, not for a cancelled update). Null is returned if the job hasn&#39;t finished once yet.
     * 
     */
    @Import(name="lastUpdated")
    private @Nullable Output<String> lastUpdated;

    /**
     * @return Timestamp when the update finished (only for a successful or failed update, not for a cancelled update). Null is returned if the job hasn&#39;t finished once yet.
     * 
     */
    public Optional<Output<String>> lastUpdated() {
        return Optional.ofNullable(this.lastUpdated);
    }

    /**
     * Timezone of where the scheduled job takes place.
     * 
     */
    @Import(name="timezone")
    private @Nullable Output<String> timezone;

    /**
     * @return Timezone of where the scheduled job takes place.
     * 
     */
    public Optional<Output<String>> timezone() {
        return Optional.ofNullable(this.timezone);
    }

    private AgentPoolUpdateScheduleArgs() {}

    private AgentPoolUpdateScheduleArgs(AgentPoolUpdateScheduleArgs $) {
        this.cron = $.cron;
        this.delay = $.delay;
        this.duration = $.duration;
        this.lastUpdated = $.lastUpdated;
        this.timezone = $.timezone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AgentPoolUpdateScheduleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AgentPoolUpdateScheduleArgs $;

        public Builder() {
            $ = new AgentPoolUpdateScheduleArgs();
        }

        public Builder(AgentPoolUpdateScheduleArgs defaults) {
            $ = new AgentPoolUpdateScheduleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cron The schedule of the update in cron format.
         * 
         * @return builder
         * 
         */
        public Builder cron(@Nullable Output<String> cron) {
            $.cron = cron;
            return this;
        }

        /**
         * @param cron The schedule of the update in cron format.
         * 
         * @return builder
         * 
         */
        public Builder cron(String cron) {
            return cron(Output.of(cron));
        }

        /**
         * @param delay Delay in days.
         * 
         * @return builder
         * 
         */
        public Builder delay(@Nullable Output<Integer> delay) {
            $.delay = delay;
            return this;
        }

        /**
         * @param delay Delay in days.
         * 
         * @return builder
         * 
         */
        public Builder delay(Integer delay) {
            return delay(Output.of(delay));
        }

        /**
         * @param duration Duration in minutes.
         * 
         * @return builder
         * 
         */
        public Builder duration(@Nullable Output<Integer> duration) {
            $.duration = duration;
            return this;
        }

        /**
         * @param duration Duration in minutes.
         * 
         * @return builder
         * 
         */
        public Builder duration(Integer duration) {
            return duration(Output.of(duration));
        }

        /**
         * @param lastUpdated Timestamp when the update finished (only for a successful or failed update, not for a cancelled update). Null is returned if the job hasn&#39;t finished once yet.
         * 
         * @return builder
         * 
         */
        public Builder lastUpdated(@Nullable Output<String> lastUpdated) {
            $.lastUpdated = lastUpdated;
            return this;
        }

        /**
         * @param lastUpdated Timestamp when the update finished (only for a successful or failed update, not for a cancelled update). Null is returned if the job hasn&#39;t finished once yet.
         * 
         * @return builder
         * 
         */
        public Builder lastUpdated(String lastUpdated) {
            return lastUpdated(Output.of(lastUpdated));
        }

        /**
         * @param timezone Timezone of where the scheduled job takes place.
         * 
         * @return builder
         * 
         */
        public Builder timezone(@Nullable Output<String> timezone) {
            $.timezone = timezone;
            return this;
        }

        /**
         * @param timezone Timezone of where the scheduled job takes place.
         * 
         * @return builder
         * 
         */
        public Builder timezone(String timezone) {
            return timezone(Output.of(timezone));
        }

        public AgentPoolUpdateScheduleArgs build() {
            return $;
        }
    }

}
