// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EndUserMyRequestsRequesterFieldValueArgs extends com.pulumi.resources.ResourceArgs {

    public static final EndUserMyRequestsRequesterFieldValueArgs Empty = new EndUserMyRequestsRequesterFieldValueArgs();

    /**
     * The ID of a requesterField. This identifies the specific field in the approval system.
     * 
     */
    @Import(name="id", required=true)
    private Output<String> id;

    /**
     * @return The ID of a requesterField. This identifies the specific field in the approval system.
     * 
     */
    public Output<String> id() {
        return this.id;
    }

    /**
     * A human-readable description of requesterField. It&#39;s used for display purposes and is optional.
     * 
     */
    @Import(name="label")
    private @Nullable Output<String> label;

    /**
     * @return A human-readable description of requesterField. It&#39;s used for display purposes and is optional.
     * 
     */
    public Optional<Output<String>> label() {
        return Optional.ofNullable(this.label);
    }

    /**
     * Type of value for the requester field. Valid values: `DURATION`, `ISO_DATE`, `MULTISELECT`, `OKTA_USER_ID`, `SELECT`, `TEXT`.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Type of value for the requester field. Valid values: `DURATION`, `ISO_DATE`, `MULTISELECT`, `OKTA_USER_ID`, `SELECT`, `TEXT`.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * The value of requesterField, which depends on the type of the field. Used for single-value fields.
     * 
     */
    @Import(name="value")
    private @Nullable Output<String> value;

    /**
     * @return The value of requesterField, which depends on the type of the field. Used for single-value fields.
     * 
     */
    public Optional<Output<String>> value() {
        return Optional.ofNullable(this.value);
    }

    /**
     * The values of requesterField with the type MULTISELECT. If the field type is MULTISELECT, this property is required instead of `value`.
     * 
     */
    @Import(name="values")
    private @Nullable Output<List<String>> values;

    /**
     * @return The values of requesterField with the type MULTISELECT. If the field type is MULTISELECT, this property is required instead of `value`.
     * 
     */
    public Optional<Output<List<String>>> values() {
        return Optional.ofNullable(this.values);
    }

    private EndUserMyRequestsRequesterFieldValueArgs() {}

    private EndUserMyRequestsRequesterFieldValueArgs(EndUserMyRequestsRequesterFieldValueArgs $) {
        this.id = $.id;
        this.label = $.label;
        this.type = $.type;
        this.value = $.value;
        this.values = $.values;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EndUserMyRequestsRequesterFieldValueArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EndUserMyRequestsRequesterFieldValueArgs $;

        public Builder() {
            $ = new EndUserMyRequestsRequesterFieldValueArgs();
        }

        public Builder(EndUserMyRequestsRequesterFieldValueArgs defaults) {
            $ = new EndUserMyRequestsRequesterFieldValueArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of a requesterField. This identifies the specific field in the approval system.
         * 
         * @return builder
         * 
         */
        public Builder id(Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of a requesterField. This identifies the specific field in the approval system.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param label A human-readable description of requesterField. It&#39;s used for display purposes and is optional.
         * 
         * @return builder
         * 
         */
        public Builder label(@Nullable Output<String> label) {
            $.label = label;
            return this;
        }

        /**
         * @param label A human-readable description of requesterField. It&#39;s used for display purposes and is optional.
         * 
         * @return builder
         * 
         */
        public Builder label(String label) {
            return label(Output.of(label));
        }

        /**
         * @param type Type of value for the requester field. Valid values: `DURATION`, `ISO_DATE`, `MULTISELECT`, `OKTA_USER_ID`, `SELECT`, `TEXT`.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Type of value for the requester field. Valid values: `DURATION`, `ISO_DATE`, `MULTISELECT`, `OKTA_USER_ID`, `SELECT`, `TEXT`.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param value The value of requesterField, which depends on the type of the field. Used for single-value fields.
         * 
         * @return builder
         * 
         */
        public Builder value(@Nullable Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value The value of requesterField, which depends on the type of the field. Used for single-value fields.
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        /**
         * @param values The values of requesterField with the type MULTISELECT. If the field type is MULTISELECT, this property is required instead of `value`.
         * 
         * @return builder
         * 
         */
        public Builder values(@Nullable Output<List<String>> values) {
            $.values = values;
            return this;
        }

        /**
         * @param values The values of requesterField with the type MULTISELECT. If the field type is MULTISELECT, this property is required instead of `value`.
         * 
         * @return builder
         * 
         */
        public Builder values(List<String> values) {
            return values(Output.of(values));
        }

        /**
         * @param values The values of requesterField with the type MULTISELECT. If the field type is MULTISELECT, this property is required instead of `value`.
         * 
         * @return builder
         * 
         */
        public Builder values(String... values) {
            return values(List.of(values));
        }

        public EndUserMyRequestsRequesterFieldValueArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("EndUserMyRequestsRequesterFieldValueArgs", "id");
            }
            return $;
        }
    }

}
