// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.okta.inputs.GetDeviceProfile;
import com.pulumi.okta.inputs.GetDeviceResourceDisplayName;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetDevicePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDevicePlainArgs Empty = new GetDevicePlainArgs();

    /**
     * The ID of the device.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The ID of the device.
     * 
     */
    public String id() {
        return this.id;
    }

    @Import(name="profile")
    private @Nullable GetDeviceProfile profile;

    public Optional<GetDeviceProfile> profile() {
        return Optional.ofNullable(this.profile);
    }

    @Import(name="resourceDisplayName")
    private @Nullable GetDeviceResourceDisplayName resourceDisplayName;

    public Optional<GetDeviceResourceDisplayName> resourceDisplayName() {
        return Optional.ofNullable(this.resourceDisplayName);
    }

    private GetDevicePlainArgs() {}

    private GetDevicePlainArgs(GetDevicePlainArgs $) {
        this.id = $.id;
        this.profile = $.profile;
        this.resourceDisplayName = $.resourceDisplayName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDevicePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDevicePlainArgs $;

        public Builder() {
            $ = new GetDevicePlainArgs();
        }

        public Builder(GetDevicePlainArgs defaults) {
            $ = new GetDevicePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of the device.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public Builder profile(@Nullable GetDeviceProfile profile) {
            $.profile = profile;
            return this;
        }

        public Builder resourceDisplayName(@Nullable GetDeviceResourceDisplayName resourceDisplayName) {
            $.resourceDisplayName = resourceDisplayName;
            return this;
        }

        public GetDevicePlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetDevicePlainArgs", "id");
            }
            return $;
        }
    }

}
