// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;


public final class GetDeviceProfile extends com.pulumi.resources.InvokeArgs {

    public static final GetDeviceProfile Empty = new GetDeviceProfile();

    /**
     * The disk encryption type of the device.
     * 
     */
    @Import(name="diskEncryptionType", required=true)
    private String diskEncryptionType;

    /**
     * @return The disk encryption type of the device.
     * 
     */
    public String diskEncryptionType() {
        return this.diskEncryptionType;
    }

    /**
     * The display name of the device.
     * 
     */
    @Import(name="displayName", required=true)
    private String displayName;

    /**
     * @return The display name of the device.
     * 
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * The International Mobile Equipment Identity (IMEI) of the device.
     * 
     */
    @Import(name="imei", required=true)
    private String imei;

    /**
     * @return The International Mobile Equipment Identity (IMEI) of the device.
     * 
     */
    public String imei() {
        return this.imei;
    }

    /**
     * Indicates if the device is jailbroken or rooted. Only applicable to IOS and ANDROID platforms.
     * 
     */
    @Import(name="integrityJailBreak", required=true)
    private Boolean integrityJailBreak;

    /**
     * @return Indicates if the device is jailbroken or rooted. Only applicable to IOS and ANDROID platforms.
     * 
     */
    public Boolean integrityJailBreak() {
        return this.integrityJailBreak;
    }

    /**
     * The manufacturer of the device.
     * 
     */
    @Import(name="manufacturer", required=true)
    private String manufacturer;

    /**
     * @return The manufacturer of the device.
     * 
     */
    public String manufacturer() {
        return this.manufacturer;
    }

    /**
     * The Mobile Equipment Identifier (MEID) of the device.
     * 
     */
    @Import(name="meid", required=true)
    private String meid;

    /**
     * @return The Mobile Equipment Identifier (MEID) of the device.
     * 
     */
    public String meid() {
        return this.meid;
    }

    /**
     * The model of the device.
     * 
     */
    @Import(name="model", required=true)
    private String model;

    /**
     * @return The model of the device.
     * 
     */
    public String model() {
        return this.model;
    }

    /**
     * The OS version of the device.
     * 
     */
    @Import(name="osVersion", required=true)
    private String osVersion;

    /**
     * @return The OS version of the device.
     * 
     */
    public String osVersion() {
        return this.osVersion;
    }

    /**
     * The platform of the device.
     * 
     */
    @Import(name="platform", required=true)
    private String platform;

    /**
     * @return The platform of the device.
     * 
     */
    public String platform() {
        return this.platform;
    }

    /**
     * Indicates if the device is registered at Okta.
     * 
     */
    @Import(name="registered", required=true)
    private Boolean registered;

    /**
     * @return Indicates if the device is registered at Okta.
     * 
     */
    public Boolean registered() {
        return this.registered;
    }

    /**
     * Indicates if secure hardware is present on the device.
     * 
     */
    @Import(name="secureHardwarePresent", required=true)
    private Boolean secureHardwarePresent;

    /**
     * @return Indicates if secure hardware is present on the device.
     * 
     */
    public Boolean secureHardwarePresent() {
        return this.secureHardwarePresent;
    }

    /**
     * The serial number of the device.
     * 
     */
    @Import(name="serialNumber", required=true)
    private String serialNumber;

    /**
     * @return The serial number of the device.
     * 
     */
    public String serialNumber() {
        return this.serialNumber;
    }

    /**
     * The Security Identifier (SID) of the device.
     * 
     */
    @Import(name="sid", required=true)
    private String sid;

    /**
     * @return The Security Identifier (SID) of the device.
     * 
     */
    public String sid() {
        return this.sid;
    }

    /**
     * Windows Trusted Platform Module hash value.
     * 
     */
    @Import(name="tpmPublicKeyHash", required=true)
    private String tpmPublicKeyHash;

    /**
     * @return Windows Trusted Platform Module hash value.
     * 
     */
    public String tpmPublicKeyHash() {
        return this.tpmPublicKeyHash;
    }

    /**
     * MacOS Unique device identifier of the device.
     * 
     */
    @Import(name="udid", required=true)
    private String udid;

    /**
     * @return MacOS Unique device identifier of the device.
     * 
     */
    public String udid() {
        return this.udid;
    }

    private GetDeviceProfile() {}

    private GetDeviceProfile(GetDeviceProfile $) {
        this.diskEncryptionType = $.diskEncryptionType;
        this.displayName = $.displayName;
        this.imei = $.imei;
        this.integrityJailBreak = $.integrityJailBreak;
        this.manufacturer = $.manufacturer;
        this.meid = $.meid;
        this.model = $.model;
        this.osVersion = $.osVersion;
        this.platform = $.platform;
        this.registered = $.registered;
        this.secureHardwarePresent = $.secureHardwarePresent;
        this.serialNumber = $.serialNumber;
        this.sid = $.sid;
        this.tpmPublicKeyHash = $.tpmPublicKeyHash;
        this.udid = $.udid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDeviceProfile defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDeviceProfile $;

        public Builder() {
            $ = new GetDeviceProfile();
        }

        public Builder(GetDeviceProfile defaults) {
            $ = new GetDeviceProfile(Objects.requireNonNull(defaults));
        }

        /**
         * @param diskEncryptionType The disk encryption type of the device.
         * 
         * @return builder
         * 
         */
        public Builder diskEncryptionType(String diskEncryptionType) {
            $.diskEncryptionType = diskEncryptionType;
            return this;
        }

        /**
         * @param displayName The display name of the device.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param imei The International Mobile Equipment Identity (IMEI) of the device.
         * 
         * @return builder
         * 
         */
        public Builder imei(String imei) {
            $.imei = imei;
            return this;
        }

        /**
         * @param integrityJailBreak Indicates if the device is jailbroken or rooted. Only applicable to IOS and ANDROID platforms.
         * 
         * @return builder
         * 
         */
        public Builder integrityJailBreak(Boolean integrityJailBreak) {
            $.integrityJailBreak = integrityJailBreak;
            return this;
        }

        /**
         * @param manufacturer The manufacturer of the device.
         * 
         * @return builder
         * 
         */
        public Builder manufacturer(String manufacturer) {
            $.manufacturer = manufacturer;
            return this;
        }

        /**
         * @param meid The Mobile Equipment Identifier (MEID) of the device.
         * 
         * @return builder
         * 
         */
        public Builder meid(String meid) {
            $.meid = meid;
            return this;
        }

        /**
         * @param model The model of the device.
         * 
         * @return builder
         * 
         */
        public Builder model(String model) {
            $.model = model;
            return this;
        }

        /**
         * @param osVersion The OS version of the device.
         * 
         * @return builder
         * 
         */
        public Builder osVersion(String osVersion) {
            $.osVersion = osVersion;
            return this;
        }

        /**
         * @param platform The platform of the device.
         * 
         * @return builder
         * 
         */
        public Builder platform(String platform) {
            $.platform = platform;
            return this;
        }

        /**
         * @param registered Indicates if the device is registered at Okta.
         * 
         * @return builder
         * 
         */
        public Builder registered(Boolean registered) {
            $.registered = registered;
            return this;
        }

        /**
         * @param secureHardwarePresent Indicates if secure hardware is present on the device.
         * 
         * @return builder
         * 
         */
        public Builder secureHardwarePresent(Boolean secureHardwarePresent) {
            $.secureHardwarePresent = secureHardwarePresent;
            return this;
        }

        /**
         * @param serialNumber The serial number of the device.
         * 
         * @return builder
         * 
         */
        public Builder serialNumber(String serialNumber) {
            $.serialNumber = serialNumber;
            return this;
        }

        /**
         * @param sid The Security Identifier (SID) of the device.
         * 
         * @return builder
         * 
         */
        public Builder sid(String sid) {
            $.sid = sid;
            return this;
        }

        /**
         * @param tpmPublicKeyHash Windows Trusted Platform Module hash value.
         * 
         * @return builder
         * 
         */
        public Builder tpmPublicKeyHash(String tpmPublicKeyHash) {
            $.tpmPublicKeyHash = tpmPublicKeyHash;
            return this;
        }

        /**
         * @param udid MacOS Unique device identifier of the device.
         * 
         * @return builder
         * 
         */
        public Builder udid(String udid) {
            $.udid = udid;
            return this;
        }

        public GetDeviceProfile build() {
            if ($.diskEncryptionType == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "diskEncryptionType");
            }
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "displayName");
            }
            if ($.imei == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "imei");
            }
            if ($.integrityJailBreak == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "integrityJailBreak");
            }
            if ($.manufacturer == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "manufacturer");
            }
            if ($.meid == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "meid");
            }
            if ($.model == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "model");
            }
            if ($.osVersion == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "osVersion");
            }
            if ($.platform == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "platform");
            }
            if ($.registered == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "registered");
            }
            if ($.secureHardwarePresent == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "secureHardwarePresent");
            }
            if ($.serialNumber == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "serialNumber");
            }
            if ($.sid == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "sid");
            }
            if ($.tpmPublicKeyHash == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "tpmPublicKeyHash");
            }
            if ($.udid == null) {
                throw new MissingRequiredPropertyException("GetDeviceProfile", "udid");
            }
            return $;
        }
    }

}
