// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetReviewAllReviewerLevelReviewerProfile extends com.pulumi.resources.InvokeArgs {

    public static final GetReviewAllReviewerLevelReviewerProfile Empty = new GetReviewAllReviewerLevelReviewerProfile();

    @Import(name="email", required=true)
    private String email;

    public String email() {
        return this.email;
    }

    @Import(name="firstName", required=true)
    private String firstName;

    public String firstName() {
        return this.firstName;
    }

    /**
     * The ID of  review.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The ID of  review.
     * 
     */
    public String id() {
        return this.id;
    }

    @Import(name="lastName", required=true)
    private String lastName;

    public String lastName() {
        return this.lastName;
    }

    @Import(name="status", required=true)
    private String status;

    public String status() {
        return this.status;
    }

    private GetReviewAllReviewerLevelReviewerProfile() {}

    private GetReviewAllReviewerLevelReviewerProfile(GetReviewAllReviewerLevelReviewerProfile $) {
        this.email = $.email;
        this.firstName = $.firstName;
        this.id = $.id;
        this.lastName = $.lastName;
        this.status = $.status;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetReviewAllReviewerLevelReviewerProfile defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetReviewAllReviewerLevelReviewerProfile $;

        public Builder() {
            $ = new GetReviewAllReviewerLevelReviewerProfile();
        }

        public Builder(GetReviewAllReviewerLevelReviewerProfile defaults) {
            $ = new GetReviewAllReviewerLevelReviewerProfile(Objects.requireNonNull(defaults));
        }

        public Builder email(String email) {
            $.email = email;
            return this;
        }

        public Builder firstName(String firstName) {
            $.firstName = firstName;
            return this;
        }

        /**
         * @param id The ID of  review.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public Builder lastName(String lastName) {
            $.lastName = lastName;
            return this;
        }

        public Builder status(String status) {
            $.status = status;
            return this;
        }

        public GetReviewAllReviewerLevelReviewerProfile build() {
            if ($.email == null) {
                throw new MissingRequiredPropertyException("GetReviewAllReviewerLevelReviewerProfile", "email");
            }
            if ($.firstName == null) {
                throw new MissingRequiredPropertyException("GetReviewAllReviewerLevelReviewerProfile", "firstName");
            }
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetReviewAllReviewerLevelReviewerProfile", "id");
            }
            if ($.lastName == null) {
                throw new MissingRequiredPropertyException("GetReviewAllReviewerLevelReviewerProfile", "lastName");
            }
            if ($.status == null) {
                throw new MissingRequiredPropertyException("GetReviewAllReviewerLevelReviewerProfile", "status");
            }
            return $;
        }
    }

}
