// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetReviewEntitlementValue extends com.pulumi.resources.InvokeArgs {

    public static final GetReviewEntitlementValue Empty = new GetReviewEntitlementValue();

    /**
     * The ID of  review.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The ID of  review.
     * 
     */
    public String id() {
        return this.id;
    }

    @Import(name="name", required=true)
    private String name;

    public String name() {
        return this.name;
    }

    private GetReviewEntitlementValue() {}

    private GetReviewEntitlementValue(GetReviewEntitlementValue $) {
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetReviewEntitlementValue defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetReviewEntitlementValue $;

        public Builder() {
            $ = new GetReviewEntitlementValue();
        }

        public Builder(GetReviewEntitlementValue defaults) {
            $ = new GetReviewEntitlementValue(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of  review.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetReviewEntitlementValue build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetReviewEntitlementValue", "id");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetReviewEntitlementValue", "name");
            }
            return $;
        }
    }

}
