// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetRequestV2RequestedFor extends com.pulumi.resources.InvokeArgs {

    public static final GetRequestV2RequestedFor Empty = new GetRequestV2RequestedFor();

    /**
     * The ID of the Okta user.
     * 
     */
    @Import(name="externalId", required=true)
    private String externalId;

    /**
     * @return The ID of the Okta user.
     * 
     */
    public String externalId() {
        return this.externalId;
    }

    /**
     * The type of principal.
     * 
     */
    @Import(name="type", required=true)
    private String type;

    /**
     * @return The type of principal.
     * 
     */
    public String type() {
        return this.type;
    }

    private GetRequestV2RequestedFor() {}

    private GetRequestV2RequestedFor(GetRequestV2RequestedFor $) {
        this.externalId = $.externalId;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRequestV2RequestedFor defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRequestV2RequestedFor $;

        public Builder() {
            $ = new GetRequestV2RequestedFor();
        }

        public Builder(GetRequestV2RequestedFor defaults) {
            $ = new GetRequestV2RequestedFor(Objects.requireNonNull(defaults));
        }

        /**
         * @param externalId The ID of the Okta user.
         * 
         * @return builder
         * 
         */
        public Builder externalId(String externalId) {
            $.externalId = externalId;
            return this;
        }

        /**
         * @param type The type of principal.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            $.type = type;
            return this;
        }

        public GetRequestV2RequestedFor build() {
            if ($.externalId == null) {
                throw new MissingRequiredPropertyException("GetRequestV2RequestedFor", "externalId");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("GetRequestV2RequestedFor", "type");
            }
            return $;
        }
    }

}
