// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PostAuthSessionPolicyRuleState extends com.pulumi.resources.ResourceArgs {

    public static final PostAuthSessionPolicyRuleState Empty = new PostAuthSessionPolicyRuleState();

    /**
     * List of group IDs to exclude from this rule.
     * 
     */
    @Import(name="groupsExcluded")
    private @Nullable Output<List<String>> groupsExcluded;

    /**
     * @return List of group IDs to exclude from this rule.
     * 
     */
    public Optional<Output<List<String>>> groupsExcluded() {
        return Optional.ofNullable(this.groupsExcluded);
    }

    /**
     * List of group IDs to include in this rule.
     * 
     */
    @Import(name="groupsIncluded")
    private @Nullable Output<List<String>> groupsIncluded;

    /**
     * @return List of group IDs to include in this rule.
     * 
     */
    public Optional<Output<List<String>>> groupsIncluded() {
        return Optional.ofNullable(this.groupsIncluded);
    }

    /**
     * Name of the policy rule.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the policy rule.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * ID of the Post Auth Session Policy. Use the `okta.getPostAuthSessionPolicy` data source to get this ID.
     * 
     */
    @Import(name="policyId")
    private @Nullable Output<String> policyId;

    /**
     * @return ID of the Post Auth Session Policy. Use the `okta.getPostAuthSessionPolicy` data source to get this ID.
     * 
     */
    public Optional<Output<String>> policyId() {
        return Optional.ofNullable(this.policyId);
    }

    /**
     * Status of the rule: `ACTIVE` or `INACTIVE`. Default is `ACTIVE`.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return Status of the rule: `ACTIVE` or `INACTIVE`. Default is `ACTIVE`.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * When true, terminates the user&#39;s session when a policy failure is detected. Default is `false`.
     * 
     */
    @Import(name="terminateSession")
    private @Nullable Output<Boolean> terminateSession;

    /**
     * @return When true, terminates the user&#39;s session when a policy failure is detected. Default is `false`.
     * 
     */
    public Optional<Output<Boolean>> terminateSession() {
        return Optional.ofNullable(this.terminateSession);
    }

    /**
     * List of user IDs to exclude from this rule.
     * 
     */
    @Import(name="usersExcluded")
    private @Nullable Output<List<String>> usersExcluded;

    /**
     * @return List of user IDs to exclude from this rule.
     * 
     */
    public Optional<Output<List<String>>> usersExcluded() {
        return Optional.ofNullable(this.usersExcluded);
    }

    /**
     * ID of the Okta Workflow to run when a policy failure is detected.
     * 
     */
    @Import(name="workflowId")
    private @Nullable Output<String> workflowId;

    /**
     * @return ID of the Okta Workflow to run when a policy failure is detected.
     * 
     */
    public Optional<Output<String>> workflowId() {
        return Optional.ofNullable(this.workflowId);
    }

    private PostAuthSessionPolicyRuleState() {}

    private PostAuthSessionPolicyRuleState(PostAuthSessionPolicyRuleState $) {
        this.groupsExcluded = $.groupsExcluded;
        this.groupsIncluded = $.groupsIncluded;
        this.name = $.name;
        this.policyId = $.policyId;
        this.status = $.status;
        this.terminateSession = $.terminateSession;
        this.usersExcluded = $.usersExcluded;
        this.workflowId = $.workflowId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PostAuthSessionPolicyRuleState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PostAuthSessionPolicyRuleState $;

        public Builder() {
            $ = new PostAuthSessionPolicyRuleState();
        }

        public Builder(PostAuthSessionPolicyRuleState defaults) {
            $ = new PostAuthSessionPolicyRuleState(Objects.requireNonNull(defaults));
        }

        /**
         * @param groupsExcluded List of group IDs to exclude from this rule.
         * 
         * @return builder
         * 
         */
        public Builder groupsExcluded(@Nullable Output<List<String>> groupsExcluded) {
            $.groupsExcluded = groupsExcluded;
            return this;
        }

        /**
         * @param groupsExcluded List of group IDs to exclude from this rule.
         * 
         * @return builder
         * 
         */
        public Builder groupsExcluded(List<String> groupsExcluded) {
            return groupsExcluded(Output.of(groupsExcluded));
        }

        /**
         * @param groupsExcluded List of group IDs to exclude from this rule.
         * 
         * @return builder
         * 
         */
        public Builder groupsExcluded(String... groupsExcluded) {
            return groupsExcluded(List.of(groupsExcluded));
        }

        /**
         * @param groupsIncluded List of group IDs to include in this rule.
         * 
         * @return builder
         * 
         */
        public Builder groupsIncluded(@Nullable Output<List<String>> groupsIncluded) {
            $.groupsIncluded = groupsIncluded;
            return this;
        }

        /**
         * @param groupsIncluded List of group IDs to include in this rule.
         * 
         * @return builder
         * 
         */
        public Builder groupsIncluded(List<String> groupsIncluded) {
            return groupsIncluded(Output.of(groupsIncluded));
        }

        /**
         * @param groupsIncluded List of group IDs to include in this rule.
         * 
         * @return builder
         * 
         */
        public Builder groupsIncluded(String... groupsIncluded) {
            return groupsIncluded(List.of(groupsIncluded));
        }

        /**
         * @param name Name of the policy rule.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the policy rule.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param policyId ID of the Post Auth Session Policy. Use the `okta.getPostAuthSessionPolicy` data source to get this ID.
         * 
         * @return builder
         * 
         */
        public Builder policyId(@Nullable Output<String> policyId) {
            $.policyId = policyId;
            return this;
        }

        /**
         * @param policyId ID of the Post Auth Session Policy. Use the `okta.getPostAuthSessionPolicy` data source to get this ID.
         * 
         * @return builder
         * 
         */
        public Builder policyId(String policyId) {
            return policyId(Output.of(policyId));
        }

        /**
         * @param status Status of the rule: `ACTIVE` or `INACTIVE`. Default is `ACTIVE`.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status Status of the rule: `ACTIVE` or `INACTIVE`. Default is `ACTIVE`.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        /**
         * @param terminateSession When true, terminates the user&#39;s session when a policy failure is detected. Default is `false`.
         * 
         * @return builder
         * 
         */
        public Builder terminateSession(@Nullable Output<Boolean> terminateSession) {
            $.terminateSession = terminateSession;
            return this;
        }

        /**
         * @param terminateSession When true, terminates the user&#39;s session when a policy failure is detected. Default is `false`.
         * 
         * @return builder
         * 
         */
        public Builder terminateSession(Boolean terminateSession) {
            return terminateSession(Output.of(terminateSession));
        }

        /**
         * @param usersExcluded List of user IDs to exclude from this rule.
         * 
         * @return builder
         * 
         */
        public Builder usersExcluded(@Nullable Output<List<String>> usersExcluded) {
            $.usersExcluded = usersExcluded;
            return this;
        }

        /**
         * @param usersExcluded List of user IDs to exclude from this rule.
         * 
         * @return builder
         * 
         */
        public Builder usersExcluded(List<String> usersExcluded) {
            return usersExcluded(Output.of(usersExcluded));
        }

        /**
         * @param usersExcluded List of user IDs to exclude from this rule.
         * 
         * @return builder
         * 
         */
        public Builder usersExcluded(String... usersExcluded) {
            return usersExcluded(List.of(usersExcluded));
        }

        /**
         * @param workflowId ID of the Okta Workflow to run when a policy failure is detected.
         * 
         * @return builder
         * 
         */
        public Builder workflowId(@Nullable Output<String> workflowId) {
            $.workflowId = workflowId;
            return this;
        }

        /**
         * @param workflowId ID of the Okta Workflow to run when a policy failure is detected.
         * 
         * @return builder
         * 
         */
        public Builder workflowId(String workflowId) {
            return workflowId(Output.of(workflowId));
        }

        public PostAuthSessionPolicyRuleState build() {
            return $;
        }
    }

}
