// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RateLimitingUseCaseModeOverridesArgs extends com.pulumi.resources.ResourceArgs {

    public static final RateLimitingUseCaseModeOverridesArgs Empty = new RateLimitingUseCaseModeOverridesArgs();

    @Import(name="loginPage")
    private @Nullable Output<String> loginPage;

    public Optional<Output<String>> loginPage() {
        return Optional.ofNullable(this.loginPage);
    }

    @Import(name="oauth2Authorize")
    private @Nullable Output<String> oauth2Authorize;

    public Optional<Output<String>> oauth2Authorize() {
        return Optional.ofNullable(this.oauth2Authorize);
    }

    @Import(name="oieAppIntent")
    private @Nullable Output<String> oieAppIntent;

    public Optional<Output<String>> oieAppIntent() {
        return Optional.ofNullable(this.oieAppIntent);
    }

    private RateLimitingUseCaseModeOverridesArgs() {}

    private RateLimitingUseCaseModeOverridesArgs(RateLimitingUseCaseModeOverridesArgs $) {
        this.loginPage = $.loginPage;
        this.oauth2Authorize = $.oauth2Authorize;
        this.oieAppIntent = $.oieAppIntent;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RateLimitingUseCaseModeOverridesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RateLimitingUseCaseModeOverridesArgs $;

        public Builder() {
            $ = new RateLimitingUseCaseModeOverridesArgs();
        }

        public Builder(RateLimitingUseCaseModeOverridesArgs defaults) {
            $ = new RateLimitingUseCaseModeOverridesArgs(Objects.requireNonNull(defaults));
        }

        public Builder loginPage(@Nullable Output<String> loginPage) {
            $.loginPage = loginPage;
            return this;
        }

        public Builder loginPage(String loginPage) {
            return loginPage(Output.of(loginPage));
        }

        public Builder oauth2Authorize(@Nullable Output<String> oauth2Authorize) {
            $.oauth2Authorize = oauth2Authorize;
            return this;
        }

        public Builder oauth2Authorize(String oauth2Authorize) {
            return oauth2Authorize(Output.of(oauth2Authorize));
        }

        public Builder oieAppIntent(@Nullable Output<String> oieAppIntent) {
            $.oieAppIntent = oieAppIntent;
            return this;
        }

        public Builder oieAppIntent(String oieAppIntent) {
            return oieAppIntent(Output.of(oieAppIntent));
        }

        public RateLimitingUseCaseModeOverridesArgs build() {
            return $;
        }
    }

}
