// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RoleSubscriptionState extends com.pulumi.resources.ResourceArgs {

    public static final RoleSubscriptionState Empty = new RoleSubscriptionState();

    /**
     * Type of the notification. Valid values:
     * 	- &#39;CONNECTOR_AGENT&#39; -  Disconnects and reconnects: On-prem provisioning, on-prem MFA agents, and RADIUS server agent.
     * 	- &#39;USER_LOCKED_OUT&#39; - User lockouts.
     * 	- &#39;APP_IMPORT&#39; - App user import status.
     * 	- &#39;LDAP_AGENT&#39; - Disconnects and reconnects: LDAP agent.
     * 	- &#39;AD_AGENT&#39; - Disconnects and reconnects: AD agent.
     * 	- &#39;OKTA_ANNOUNCEMENT&#39; - Okta release notes and announcements.
     * 	- &#39;OKTA_UPDATE&#39; - Scheduled system updates.
     * 	- &#39;IWA_AGENT&#39; - Disconnects and reconnects: IWA agent.
     * 	- &#39;USER_DEPROVISION&#39; - User deprovisions.
     * 	- &#39;REPORT_SUSPICIOUS_ACTIVITY&#39; - User reporting of suspicious activity.
     * 	- &#39;RATELIMIT_NOTIFICATION&#39; - Rate limit warning and violation.
     * 	- &#39;AGENT_AUTO_UPDATE_NOTIFICATION&#39; - Agent auto-update notifications: AD Agent.
     * 
     */
    @Import(name="notificationType")
    private @Nullable Output<String> notificationType;

    /**
     * @return Type of the notification. Valid values:
     * 	- &#39;CONNECTOR_AGENT&#39; -  Disconnects and reconnects: On-prem provisioning, on-prem MFA agents, and RADIUS server agent.
     * 	- &#39;USER_LOCKED_OUT&#39; - User lockouts.
     * 	- &#39;APP_IMPORT&#39; - App user import status.
     * 	- &#39;LDAP_AGENT&#39; - Disconnects and reconnects: LDAP agent.
     * 	- &#39;AD_AGENT&#39; - Disconnects and reconnects: AD agent.
     * 	- &#39;OKTA_ANNOUNCEMENT&#39; - Okta release notes and announcements.
     * 	- &#39;OKTA_UPDATE&#39; - Scheduled system updates.
     * 	- &#39;IWA_AGENT&#39; - Disconnects and reconnects: IWA agent.
     * 	- &#39;USER_DEPROVISION&#39; - User deprovisions.
     * 	- &#39;REPORT_SUSPICIOUS_ACTIVITY&#39; - User reporting of suspicious activity.
     * 	- &#39;RATELIMIT_NOTIFICATION&#39; - Rate limit warning and violation.
     * 	- &#39;AGENT_AUTO_UPDATE_NOTIFICATION&#39; - Agent auto-update notifications: AD Agent.
     * 
     */
    public Optional<Output<String>> notificationType() {
        return Optional.ofNullable(this.notificationType);
    }

    /**
     * Type of the role. Valid values:
     * 	&#39;API_ADMIN&#39;,
     * 	&#39;APP_ADMIN&#39;,
     * 	&#39;CUSTOM&#39;,
     * 	&#39;GROUP_MEMBERSHIP_ADMIN&#39;,
     * 	&#39;HELP_DESK_ADMIN&#39;,
     * 	&#39;MOBILE_ADMIN&#39;,
     * 	&#39;ORG_ADMIN&#39;,
     * 	&#39;READ_ONLY_ADMIN&#39;,
     * 	&#39;REPORT_ADMIN&#39;,
     * 	&#39;SUPER_ADMIN&#39;,
     * 	&#39;USER_ADMIN&#39;
     * 	. See [API docs](https://developer.okta.com/docs/reference/api/admin-notifications/#role-types).
     * 
     */
    @Import(name="roleType")
    private @Nullable Output<String> roleType;

    /**
     * @return Type of the role. Valid values:
     * 	&#39;API_ADMIN&#39;,
     * 	&#39;APP_ADMIN&#39;,
     * 	&#39;CUSTOM&#39;,
     * 	&#39;GROUP_MEMBERSHIP_ADMIN&#39;,
     * 	&#39;HELP_DESK_ADMIN&#39;,
     * 	&#39;MOBILE_ADMIN&#39;,
     * 	&#39;ORG_ADMIN&#39;,
     * 	&#39;READ_ONLY_ADMIN&#39;,
     * 	&#39;REPORT_ADMIN&#39;,
     * 	&#39;SUPER_ADMIN&#39;,
     * 	&#39;USER_ADMIN&#39;
     * 	. See [API docs](https://developer.okta.com/docs/reference/api/admin-notifications/#role-types).
     * 
     */
    public Optional<Output<String>> roleType() {
        return Optional.ofNullable(this.roleType);
    }

    /**
     * Subscription status. Valid values: `subscribed`, `unsubscribed`.
     * 
     */
    @Import(name="status")
    private @Nullable Output<String> status;

    /**
     * @return Subscription status. Valid values: `subscribed`, `unsubscribed`.
     * 
     */
    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    private RoleSubscriptionState() {}

    private RoleSubscriptionState(RoleSubscriptionState $) {
        this.notificationType = $.notificationType;
        this.roleType = $.roleType;
        this.status = $.status;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RoleSubscriptionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RoleSubscriptionState $;

        public Builder() {
            $ = new RoleSubscriptionState();
        }

        public Builder(RoleSubscriptionState defaults) {
            $ = new RoleSubscriptionState(Objects.requireNonNull(defaults));
        }

        /**
         * @param notificationType Type of the notification. Valid values:
         * 	- &#39;CONNECTOR_AGENT&#39; -  Disconnects and reconnects: On-prem provisioning, on-prem MFA agents, and RADIUS server agent.
         * 	- &#39;USER_LOCKED_OUT&#39; - User lockouts.
         * 	- &#39;APP_IMPORT&#39; - App user import status.
         * 	- &#39;LDAP_AGENT&#39; - Disconnects and reconnects: LDAP agent.
         * 	- &#39;AD_AGENT&#39; - Disconnects and reconnects: AD agent.
         * 	- &#39;OKTA_ANNOUNCEMENT&#39; - Okta release notes and announcements.
         * 	- &#39;OKTA_UPDATE&#39; - Scheduled system updates.
         * 	- &#39;IWA_AGENT&#39; - Disconnects and reconnects: IWA agent.
         * 	- &#39;USER_DEPROVISION&#39; - User deprovisions.
         * 	- &#39;REPORT_SUSPICIOUS_ACTIVITY&#39; - User reporting of suspicious activity.
         * 	- &#39;RATELIMIT_NOTIFICATION&#39; - Rate limit warning and violation.
         * 	- &#39;AGENT_AUTO_UPDATE_NOTIFICATION&#39; - Agent auto-update notifications: AD Agent.
         * 
         * @return builder
         * 
         */
        public Builder notificationType(@Nullable Output<String> notificationType) {
            $.notificationType = notificationType;
            return this;
        }

        /**
         * @param notificationType Type of the notification. Valid values:
         * 	- &#39;CONNECTOR_AGENT&#39; -  Disconnects and reconnects: On-prem provisioning, on-prem MFA agents, and RADIUS server agent.
         * 	- &#39;USER_LOCKED_OUT&#39; - User lockouts.
         * 	- &#39;APP_IMPORT&#39; - App user import status.
         * 	- &#39;LDAP_AGENT&#39; - Disconnects and reconnects: LDAP agent.
         * 	- &#39;AD_AGENT&#39; - Disconnects and reconnects: AD agent.
         * 	- &#39;OKTA_ANNOUNCEMENT&#39; - Okta release notes and announcements.
         * 	- &#39;OKTA_UPDATE&#39; - Scheduled system updates.
         * 	- &#39;IWA_AGENT&#39; - Disconnects and reconnects: IWA agent.
         * 	- &#39;USER_DEPROVISION&#39; - User deprovisions.
         * 	- &#39;REPORT_SUSPICIOUS_ACTIVITY&#39; - User reporting of suspicious activity.
         * 	- &#39;RATELIMIT_NOTIFICATION&#39; - Rate limit warning and violation.
         * 	- &#39;AGENT_AUTO_UPDATE_NOTIFICATION&#39; - Agent auto-update notifications: AD Agent.
         * 
         * @return builder
         * 
         */
        public Builder notificationType(String notificationType) {
            return notificationType(Output.of(notificationType));
        }

        /**
         * @param roleType Type of the role. Valid values:
         * 	&#39;API_ADMIN&#39;,
         * 	&#39;APP_ADMIN&#39;,
         * 	&#39;CUSTOM&#39;,
         * 	&#39;GROUP_MEMBERSHIP_ADMIN&#39;,
         * 	&#39;HELP_DESK_ADMIN&#39;,
         * 	&#39;MOBILE_ADMIN&#39;,
         * 	&#39;ORG_ADMIN&#39;,
         * 	&#39;READ_ONLY_ADMIN&#39;,
         * 	&#39;REPORT_ADMIN&#39;,
         * 	&#39;SUPER_ADMIN&#39;,
         * 	&#39;USER_ADMIN&#39;
         * 	. See [API docs](https://developer.okta.com/docs/reference/api/admin-notifications/#role-types).
         * 
         * @return builder
         * 
         */
        public Builder roleType(@Nullable Output<String> roleType) {
            $.roleType = roleType;
            return this;
        }

        /**
         * @param roleType Type of the role. Valid values:
         * 	&#39;API_ADMIN&#39;,
         * 	&#39;APP_ADMIN&#39;,
         * 	&#39;CUSTOM&#39;,
         * 	&#39;GROUP_MEMBERSHIP_ADMIN&#39;,
         * 	&#39;HELP_DESK_ADMIN&#39;,
         * 	&#39;MOBILE_ADMIN&#39;,
         * 	&#39;ORG_ADMIN&#39;,
         * 	&#39;READ_ONLY_ADMIN&#39;,
         * 	&#39;REPORT_ADMIN&#39;,
         * 	&#39;SUPER_ADMIN&#39;,
         * 	&#39;USER_ADMIN&#39;
         * 	. See [API docs](https://developer.okta.com/docs/reference/api/admin-notifications/#role-types).
         * 
         * @return builder
         * 
         */
        public Builder roleType(String roleType) {
            return roleType(Output.of(roleType));
        }

        /**
         * @param status Subscription status. Valid values: `subscribed`, `unsubscribed`.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status Subscription status. Valid values: `subscribed`, `unsubscribed`.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        public RoleSubscriptionState build() {
            return $;
        }
    }

}
