// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCampaignReviewerSettingsReviewerLevelStartReview {
    private Integer onDay;
    private String when;

    private GetCampaignReviewerSettingsReviewerLevelStartReview() {}
    public Integer onDay() {
        return this.onDay;
    }
    public String when() {
        return this.when;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCampaignReviewerSettingsReviewerLevelStartReview defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer onDay;
        private String when;
        public Builder() {}
        public Builder(GetCampaignReviewerSettingsReviewerLevelStartReview defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.onDay = defaults.onDay;
    	      this.when = defaults.when;
        }

        @CustomType.Setter
        public Builder onDay(Integer onDay) {
            if (onDay == null) {
              throw new MissingRequiredPropertyException("GetCampaignReviewerSettingsReviewerLevelStartReview", "onDay");
            }
            this.onDay = onDay;
            return this;
        }
        @CustomType.Setter
        public Builder when(String when) {
            if (when == null) {
              throw new MissingRequiredPropertyException("GetCampaignReviewerSettingsReviewerLevelStartReview", "when");
            }
            this.when = when;
            return this;
        }
        public GetCampaignReviewerSettingsReviewerLevelStartReview build() {
            final var _resultValue = new GetCampaignReviewerSettingsReviewerLevelStartReview();
            _resultValue.onDay = onDay;
            _resultValue.when = when;
            return _resultValue;
        }
    }
}
