// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCatalogEntryUserAccessRequestFieldsDataChoice {
    /**
     * @return Valid choice.
     * 
     */
    private String choice;

    private GetCatalogEntryUserAccessRequestFieldsDataChoice() {}
    /**
     * @return Valid choice.
     * 
     */
    public String choice() {
        return this.choice;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCatalogEntryUserAccessRequestFieldsDataChoice defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String choice;
        public Builder() {}
        public Builder(GetCatalogEntryUserAccessRequestFieldsDataChoice defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.choice = defaults.choice;
        }

        @CustomType.Setter
        public Builder choice(String choice) {
            if (choice == null) {
              throw new MissingRequiredPropertyException("GetCatalogEntryUserAccessRequestFieldsDataChoice", "choice");
            }
            this.choice = choice;
            return this;
        }
        public GetCatalogEntryUserAccessRequestFieldsDataChoice build() {
            final var _resultValue = new GetCatalogEntryUserAccessRequestFieldsDataChoice();
            _resultValue.choice = choice;
            return _resultValue;
        }
    }
}
