// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.okta.outputs.GetCampaignRemediationSettingsAutoRemediationSettings;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetCampaignRemediationSettings {
    /**
     * @return Specifies the action by default if the reviewer approves access. NO_ACTION indicates there is no remediation action and the user retains access.
     * 
     */
    private String accessApproved;
    /**
     * @return Specifies the action if the reviewer revokes access. NO_ACTION indicates the user retains the same access. DENY indicates the user will have their access revoked as long as they are not assigned to a group through Group Rules.
     * 
     */
    private String accessRevoked;
    private @Nullable GetCampaignRemediationSettingsAutoRemediationSettings autoRemediationSettings;
    /**
     * @return Specifies the action if the reviewer doesn&#39;t respond to the request.
     * 
     */
    private String noResponse;

    private GetCampaignRemediationSettings() {}
    /**
     * @return Specifies the action by default if the reviewer approves access. NO_ACTION indicates there is no remediation action and the user retains access.
     * 
     */
    public String accessApproved() {
        return this.accessApproved;
    }
    /**
     * @return Specifies the action if the reviewer revokes access. NO_ACTION indicates the user retains the same access. DENY indicates the user will have their access revoked as long as they are not assigned to a group through Group Rules.
     * 
     */
    public String accessRevoked() {
        return this.accessRevoked;
    }
    public Optional<GetCampaignRemediationSettingsAutoRemediationSettings> autoRemediationSettings() {
        return Optional.ofNullable(this.autoRemediationSettings);
    }
    /**
     * @return Specifies the action if the reviewer doesn&#39;t respond to the request.
     * 
     */
    public String noResponse() {
        return this.noResponse;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCampaignRemediationSettings defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accessApproved;
        private String accessRevoked;
        private @Nullable GetCampaignRemediationSettingsAutoRemediationSettings autoRemediationSettings;
        private String noResponse;
        public Builder() {}
        public Builder(GetCampaignRemediationSettings defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessApproved = defaults.accessApproved;
    	      this.accessRevoked = defaults.accessRevoked;
    	      this.autoRemediationSettings = defaults.autoRemediationSettings;
    	      this.noResponse = defaults.noResponse;
        }

        @CustomType.Setter
        public Builder accessApproved(String accessApproved) {
            if (accessApproved == null) {
              throw new MissingRequiredPropertyException("GetCampaignRemediationSettings", "accessApproved");
            }
            this.accessApproved = accessApproved;
            return this;
        }
        @CustomType.Setter
        public Builder accessRevoked(String accessRevoked) {
            if (accessRevoked == null) {
              throw new MissingRequiredPropertyException("GetCampaignRemediationSettings", "accessRevoked");
            }
            this.accessRevoked = accessRevoked;
            return this;
        }
        @CustomType.Setter
        public Builder autoRemediationSettings(@Nullable GetCampaignRemediationSettingsAutoRemediationSettings autoRemediationSettings) {

            this.autoRemediationSettings = autoRemediationSettings;
            return this;
        }
        @CustomType.Setter
        public Builder noResponse(String noResponse) {
            if (noResponse == null) {
              throw new MissingRequiredPropertyException("GetCampaignRemediationSettings", "noResponse");
            }
            this.noResponse = noResponse;
            return this;
        }
        public GetCampaignRemediationSettings build() {
            final var _resultValue = new GetCampaignRemediationSettings();
            _resultValue.accessApproved = accessApproved;
            _resultValue.accessRevoked = accessRevoked;
            _resultValue.autoRemediationSettings = autoRemediationSettings;
            _resultValue.noResponse = noResponse;
            return _resultValue;
        }
    }
}
