// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetUserSecurityQuestionsQuestion {
    /**
     * @return Security question unique key.
     * 
     */
    private String key;
    /**
     * @return Display text for security question.
     * 
     */
    private String text;

    private GetUserSecurityQuestionsQuestion() {}
    /**
     * @return Security question unique key.
     * 
     */
    public String key() {
        return this.key;
    }
    /**
     * @return Display text for security question.
     * 
     */
    public String text() {
        return this.text;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetUserSecurityQuestionsQuestion defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String key;
        private String text;
        public Builder() {}
        public Builder(GetUserSecurityQuestionsQuestion defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.key = defaults.key;
    	      this.text = defaults.text;
        }

        @CustomType.Setter
        public Builder key(String key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }
        @CustomType.Setter
        public Builder text(String text) {
            this.text = Objects.requireNonNull(text);
            return this;
        }
        public GetUserSecurityQuestionsQuestion build() {
            final var o = new GetUserSecurityQuestionsQuestion();
            o.key = key;
            o.text = text;
            return o;
        }
    }
}
