// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.okta.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.okta.outputs.UiSchemaUiSchemaElement;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class UiSchemaUiSchema {
    /**
     * @return Specifies the button label for the Submit button at the bottom of the enrollment form.
     * 
     */
    private @Nullable String buttonLabel;
    private @Nullable List<UiSchemaUiSchemaElement> elements;
    /**
     * @return Specifies the label at the top of the enrollment form under the logo.
     * 
     */
    private @Nullable String label;
    /**
     * @return Specifies the type of layout.
     * 
     */
    private @Nullable String type;

    private UiSchemaUiSchema() {}
    /**
     * @return Specifies the button label for the Submit button at the bottom of the enrollment form.
     * 
     */
    public Optional<String> buttonLabel() {
        return Optional.ofNullable(this.buttonLabel);
    }
    public List<UiSchemaUiSchemaElement> elements() {
        return this.elements == null ? List.of() : this.elements;
    }
    /**
     * @return Specifies the label at the top of the enrollment form under the logo.
     * 
     */
    public Optional<String> label() {
        return Optional.ofNullable(this.label);
    }
    /**
     * @return Specifies the type of layout.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(UiSchemaUiSchema defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String buttonLabel;
        private @Nullable List<UiSchemaUiSchemaElement> elements;
        private @Nullable String label;
        private @Nullable String type;
        public Builder() {}
        public Builder(UiSchemaUiSchema defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.buttonLabel = defaults.buttonLabel;
    	      this.elements = defaults.elements;
    	      this.label = defaults.label;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder buttonLabel(@Nullable String buttonLabel) {

            this.buttonLabel = buttonLabel;
            return this;
        }
        @CustomType.Setter
        public Builder elements(@Nullable List<UiSchemaUiSchemaElement> elements) {

            this.elements = elements;
            return this;
        }
        public Builder elements(UiSchemaUiSchemaElement... elements) {
            return elements(List.of(elements));
        }
        @CustomType.Setter
        public Builder label(@Nullable String label) {

            this.label = label;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        public UiSchemaUiSchema build() {
            final var _resultValue = new UiSchemaUiSchema();
            _resultValue.buttonLabel = buttonLabel;
            _resultValue.elements = elements;
            _resultValue.label = label;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
