// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Okta.Policy.Outputs
{

    [OutputType]
    public sealed class RuleIdpDiscoveryAppExclude
    {
        /// <summary>
        /// Use if `type` is `"APP"` to indicate the application id to include.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// Use if the `type` is `"APP_TYPE"` to indicate the type of application(s) to include in instances where an entire group (i.e. `yahoo_mail`) of applications should be included.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// One of: `"ANY"`, `"MOBILE"`, `"DESKTOP"`
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private RuleIdpDiscoveryAppExclude(
            string? id,

            string? name,

            string? type)
        {
            Id = id;
            Name = name;
            Type = type;
        }
    }
}
