// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Retrieves Okta ThreatInsight Settings.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as okta from "@pulumi/okta";
 *
 * const example = okta.getThreatInsightSettings({});
 * ```
 */
export function getThreatInsightSettings(args?: GetThreatInsightSettingsArgs, opts?: pulumi.InvokeOptions): Promise<GetThreatInsightSettingsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("okta:index/getThreatInsightSettings:getThreatInsightSettings", {
        "id": args.id,
        "items": args.items,
    }, opts);
}

/**
 * A collection of arguments for invoking getThreatInsightSettings.
 */
export interface GetThreatInsightSettingsArgs {
    /**
     * Unique identifier of the threat*insight*settings.
     */
    id?: string;
    /**
     * List of ThreatInsight settings.
     */
    items?: inputs.GetThreatInsightSettingsItem[];
}

/**
 * A collection of values returned by getThreatInsightSettings.
 */
export interface GetThreatInsightSettingsResult {
    /**
     * Unique identifier of the threat*insight*settings.
     */
    readonly id: string;
    /**
     * List of ThreatInsight settings.
     */
    readonly items?: outputs.GetThreatInsightSettingsItem[];
}
/**
 * Retrieves Okta ThreatInsight Settings.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as okta from "@pulumi/okta";
 *
 * const example = okta.getThreatInsightSettings({});
 * ```
 */
export function getThreatInsightSettingsOutput(args?: GetThreatInsightSettingsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetThreatInsightSettingsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("okta:index/getThreatInsightSettings:getThreatInsightSettings", {
        "id": args.id,
        "items": args.items,
    }, opts);
}

/**
 * A collection of arguments for invoking getThreatInsightSettings.
 */
export interface GetThreatInsightSettingsOutputArgs {
    /**
     * Unique identifier of the threat*insight*settings.
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * List of ThreatInsight settings.
     */
    items?: pulumi.Input<pulumi.Input<inputs.GetThreatInsightSettingsItemArgs>[] | undefined>;
}
